### ISSUE TITLE
PJAX request errors

### ISSUE THREAD

**Issue by antonkomarev** [Riari/laravel-forum#100]
Default error page content block has escaped error page which should be displayed:

![selection_059](https://cloud.githubusercontent.com/assets/1849174/12214152/3b61d596-b69a-11e5-8dce-d42fa20d9677.png)

Using Laravel 5.2

**Comment by antonkomarev** [comment]
I suppose the problem is:

> exception 'ErrorException' with message 'Argument 2 passed to Riari\Forum\Frontend\Http\Controllers\BaseController::handleResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in /home/Development/forum/vendor/riari/laravel-forum/src/API/Dispatcher.php on line 137 and defined' in /home/Development/forum/vendor/riari/laravel-forum-frontend/src/Http/Controllers/BaseController.php:52

**Comment by antonkomarev** [comment]
Sorry, my bad. This error hapenning when I'm performing PAJAX requests: https://github.com/spatie/laravel-pjax
That only hapenning on forums, other packages are working well with PJAX requests.

**Comment by Riari** [comment]
Looks like it's due to the internal request dispatching. I'll investigate when I can.

**Comment by antonkomarev** [comment]
Hmm... maybe this would help to resolve it:
https://github.com/laravel/framework/pull/11850

**Comment by Riari** [comment]
Seems likely. Would you be willing to test it on your install?
