### ISSUE TITLE
How to add forum routes to 'web' route groups to avoid errors

### ISSUE THREAD

**Issue by jerryOkafor** [Riari/laravel-forum#102]
i have succeeded in integrating laravel and forum but one thing is left, the web guard middleware enbles session in laravel 5.2, so when i run /forum i get this errors:

ErrorException in 6829460faf86e4b23bc8a19c8baa92dc4b035c9e.php line 7:
Undefined variable: errors (View: C:\wamp\www\agron\resources\views\vendor\forum\partials\alerts.blade.php) (View: C:\wamp\www\agron\resources\views\vendor\forum\partials\alerts.blade.php) (View: C:\wamp\www\agron\resources\views\vendor\forum\partials\alerts.blade.php)

**Comment by antonkomarev** [comment]
@jerryhanks take a look: #97

**Comment by jerryOkafor** [comment]
This does not solve my problem, if any one has used the forum with laravel 5.2 then they should tell me.

**Comment by Riari** [comment]
I did, and I couldn't reproduce the issue. Did you set `forum.frontend.middleware` to `web`?

**Comment by jerryOkafor** [comment]
which folder is it. One more thing, i have installed it and the only thing i see is a page with no link for creating a category or thread or post or comment/reply, how can i start using it.

**Comment by Riari** [comment]
After publishing config via `artisan vendor:publish`, you'll find the option in config/forum.frontend.php.

Are you logged in? If so, are you using Laravel's standard auth or a third party authentication package? The forum uses Laravel's built-in Auth classes.

**Comment by jerryOkafor** [comment]
I am loged in and I am using larval standard Auth,

**Comment by jerryOkafor** [comment]
I have seen a link to create a new category but i get this error after creating a new catgeory

FatalErrorException in BaseModel.php line 138:
Call to a member function parameterNames() on a non-object

**Comment by Riari** [comment]
This is weird, but I have a feeling you're somehow using old package files. I say that because the line number in the current BaseModel for the line in question is 144, not 138. It moved down as of 3.0.2 with the addition of `@deprecated` and `@todo` lines.

Make sure you're using the latest version and that error should go away.

**Comment by jerryOkafor** [comment]
I am using 3.0

**Comment by jerryOkafor** [comment]
How do I update to the latest packed cos I just installed this package according the commands in the readme.md.

**Comment by antonkomarev** [comment]
A bit crunchy method, but it will do the trick.

Remove there lines from `composer.json` in your laravel root folder:

``` json
"riari/laravel-forum": "~3.0",
"riari/laravel-forum-frontend": "~1.0",
```

Then run `composer update`. It will remove package from your application.

After that you can install forum again from documentation.
