### ISSUE TITLE
When i finished installing the package and once i create a category i get this errors below

### ISSUE THREAD

**Issue by jerryOkafor** [Riari/laravel-forum#104]
## Help Please it is important

FatalErrorException in BaseModel.php line 138:
Call to a member function parameterNames() on a non-object

**Comment by Riari** [comment]
I already explained why this is happening. You're using old package files - I'm not sure how, but I'm certain that's the case. All I can suggest based on this is that you check your composer dependencies and run composer update.

Also, demanding help when I'm asleep isn't going to help you. If I take a while to respond to an issue there's a reason for it.

**Comment by jerryOkafor** [comment]
Thank u, for ur time. I will work on that.
