### ISSUE TITLE
Authorization based Category View Abilities

### ISSUE THREAD

**Issue by Gummibeer** [Riari/laravel-forum#106]
Hey,

it would be great if there will be any way to save an ability for the categories to view, edit, post.

Example:

You have an open Forum for everyone but also have a team and want an internal category just for the team-members. And inside this category it would be cool if you can create subcategories with detailed abilities for development, graphics or whatever parts you have in your team.
In the code it would be cool if it will work with the Laravel 5.1 integrated Authorization System, like:

```
@can($category->required_ability, $category)
\Auth::User()->can($category->required_ability, $category)
$this->authorize($category->required_ability, $category)
```

So primary just an optional text field/dropdown where the dev that uses this package can enter their abilities that are possible.

Something like an extended private/public for categories.

**Comment by Riari** [comment]
I like the idea in principle, but I'm not convinced it's necessary. You already have the option of applying this logic in the Category policy and I'm not sure what kind of custom abilities you'd need to dynamically define.

For example, if you wanted to limit the visibility of categories to certain teams then you'd override the `Category::view` method and use the `$category` and `$user` objects in it to determine whether or not they should see it.

Sorry if I'm overlooking something - maybe you could give a more specific example?

**Comment by Gummibeer** [comment]
The Main Problem for isn't to apply these things to controller, view but to save which ability is necessary to view this category.

Do you have any hint how to do this?

**Comment by Riari** [comment]
Just use the `Category::view` ability. How exactly you use it is up to you, but presumably you have user groups or roles of some kind, so one thing you could do is define an array in your config somewhere mapping category IDs with user group IDs, then [override the `Category::view()` policy class method](http://teamteatime.net/docs/laravel-forum/3.x/policies.md).

Here's a vague example with a made up config key and user group ID property:

```
    /**
     * Permission: View category. Only takes effect for 'private' categories.
     *
     * @param  object  $user
     * @param  Category  $category
     * @return bool
     */
    public function view($user, Category $category)
    {
        $categoryGroups = config('forum.integration.category.groups');
        return in_array($user->group->id, $categoryGroups[$category->id]);
    }
```

Edit: you could of course write something a lot more elegant than that, but you get the idea. Permissions can be as granular as you like, you just have to encapsulate them in the given abilities.

**Comment by Gummibeer** [comment]
Ok, the mapping idea isn't the rly cool way - but if you won't add/extend this, what I understand cause it is very special, I will add a additional table with the relations, the php-mapping isn't so good for a growing forum.
But thanks for the hints! :)

**Comment by Riari** [comment]
Well, I know practically nothing about your forum - it was just an example. I'd probably use a model too.

Thanks for your understanding :)
