### ISSUE TITLE
Integration Problems with existing schema

### ISSUE THREAD

**Issue by NicholasSmith753** [Riari/laravel-forum#109]
Hi Riari,

I am currently trying to integrate your forum package with an existing application with multiple user models in Laravel 5.1. After setting up the forum I logged into a user account and was able to navigate to the forum and set up a category. The problem came when I needed to set up a thread, when I entered the test data and submitted I got an error stating that 'author_id is required'. 

I did some looking around in the code and realized it was originating in the validator block of the create() in the ThreadController in the forum-frontend package. However, I am not sure how to approach the problem without degrading the package's ability to smoothly upgrade to the next version. 

Can you please instruct me on how to resolve this issue?

Thanks

Nicholas Smith

**Comment by Riari** [comment]
I'm going to take a wild guess that your user table's primary key isn't "id", in which case you'll need to define a `getIdAttribute()` that returns the user ID so that the forum's references to the `id` property on user objects will work.

If that's not the case, it may be a session issue - are you sure you were still logged in by the time you submitted the form?

**Comment by NicholasSmith753** [comment]
Hi Riari,

That would be correct, my user models do not use id as the primary attribute. Based on what you suggested I found this link on the Laravel documentation site which outlines setting up an accessor for a model for data manipulation purposes https://laravel.com/docs/5.1/eloquent-mutators. 

Is that what you meant by creating a getIdAttribute()? If so, I would have to run an eloquent query to get the value from the database as outlined in the documentation.

**Comment by Riari** [comment]
Just define it like so in your model:

```
public function getIdAttribute() {
    return $this->whatever_the_id_column_is;
}
```

This isn't a documented use of attribute getters, but it's very useful and shouldn't incur another query. It will simply result in `$user->id` returning the same value as the original attribute for the column.

**Comment by NicholasSmith753** [comment]
Hi Riari,

That did the trick thanks a lot for your assistance.
