### ISSUE TITLE
Auth::check() being disabled

### ISSUE THREAD

**Issue by felorhik** [Riari/laravel-forum#111]
This is more then likely me overlooking something, or just plain something wrong in my app and I intend to update this when I come up with the solution. If Its something in my app I wanted to document it for anyone who runs into it so they can come up with a solution. If not well I will detail out as much as possible.

Basically in one of my main application partials I am using `Auth::check()` to change part of the menu for who is logged in. If they are it will show things like account or login and if not login/register, normal stuff basically. However when logged in it is returning false when the user is logged in, but only on forum routes.

So far I have tried messing with the location of the service providers but same effect. The only real difference is I am not adding auth middleware into the forum routes where the rest have it.

I will update this If I find out what is wrong, so far I really like the amount of time this package could save with having an integrated, so I really want to make it work :D

**Comment by felorhik** [comment]
Found it like the minute after I posted this.

It is an issue with compatibility by default with laravel 5.2.

5.2 assumes auth routes have a middleware of "web" so that needs to be added to the `forum.frontend.php` config. It is a simple fix if you know what it is but to fix it in the package would likely break compatibility with 5.1 for that version, probably not the best idea for something so simple.

**Comment by Riari** [comment]
Yeah, it's a known issue, and the config doesn't have "web" as a default for precisely the reason you mentioned. I should probably put a note about that in the readme and docs.

**Comment by felorhik** [comment]
Might be an idea, but I got another one after thinking about it a bit.

If you use the `Forum` class to add a function `Forum::routes()` to create the routes, similar to how `Route::auth()` works then the user could put it into their own routes, inside the web config.

This also will allow them to use the frontend package, but create their own routes as well rather then be forced to use the ones created in the service provider.

Just an idea though :P
