### ISSUE TITLE
Check if category contains unread posts

### ISSUE THREAD

**Issue by mydnic** [Riari/laravel-forum#116]
Hello,
I don't if this something you've planned to do, or not, but it would be very nice to be able to check if a category contains any unread posts.
It would allow to display a colored icon or something in front of the category that has one or more unread post.

This feature exists on almost every forum so I guess it's something a lot of people would be interested in ?

I hope my explanations are understandable :)

Thanks in advance

**Comment by daniperdana** [comment]
yeas its nice its like notification on facebook.
i think comshar.com has implement samething like that.you can check out their site https://comshar.com
so on comshar.com if you create discussion then if someone post on it ,it will on notification page.

i can give method to you if you are interesting

**Comment by Riari** [comment]
I like the idea of unread/read tracking per category. Notifications are a little different as I imagine them only being applicable in a "subscribe to category" kind of way, which is a whole different problem.

I need to look at how threads are tracked currently to see if this is feasible without impacting performance too much.

Thanks for the suggestion :)

**Comment by mydnic** [comment]
Yeah it's not related to notifications and category "subscription" (which I think is easily doable yourself in your app using Events).

I guess that this unread check is doable in one query per category but I don't know how to handle sub level categories :/

**Comment by Gummibeer** [comment]
@Riari I think that it should be solveable by joins and counts, something like:

``` php
if($category->threads()->count() > $category->threads()->readed()->count()) {
    // category has unread threads/posts
}
```

``` php
class Thread {
    ....
    public function scopeReaded($query) {
        $thread = $this;
        $query->whereHas('readers', function($subquery) use ($thread) {
            $subquery
                ->where('user_id', \Auth::id())
                ->where('updated_at', '>=', $thread->updated_at);
        });
    }
    ...
}
```

If I haven't missed something this should work!?

**Comment by unbolt** [comment]
I've written the query to find it, if anyone can eloquentise it for a getUnreadThreadsAttribute() function on the Categories model:

```
select t.id, t.title, t.updated_at
from forum_threads t
where t.id not in
(
select t.id
from forum_threads t
    join forum_threads_read r
    on r.thread_id = t.id

where t.updated_at <= r.updated_at
and r.user_id = <auth user id>
)
and t.updated_at > <new posts time variable>
```

**Comment by unbolt** [comment]
- t.category_id = $this->id, obvs ;(

**Comment by unbolt** [comment]
This appears to give me the expected results:

```
        $time = time();
        $age = strtotime(config('forum.preferences.old_thread_threshold'), 0);
        $cutoff = $time - $age;

        $select = DB::table('forum_threads')
                        ->whereNotIn('forum_threads.id', function($query) {
                            $query->select('forum_threads.id')
                                  ->from('forum_threads')
                                  ->join('forum_threads_read', 'forum_threads_read.thread_id', '=', 'forum_threads.id')
                                  ->where('forum_threads_read.user_id', '=', \Auth::id())
                                  ->where('forum_threads_read.updated_at', '<=', 'forum_threads.updated_at');
                        })
                        ->where('forum_threads.updated_at', '>', date('Y-m-d H:i:s', $cutoff))
                        ->where('forum_threads.category_id', '=', $this->id)
                        ->get();
```

**Comment by unbolt** [comment]
Needs a little adjustment, only getting ID will speed things up, or I am sure you can do some kind of count() type thing in laravel, still working on it but definitely possible with the information available in just one query per category.

**Comment by unbolt** [comment]
This is how I did it in the end:

```
public function getHasNewPostsAttribute()
    {
        if(!\Auth::id()) {
            return false;
        }

        $time = time();
        $age = strtotime(config('forum.preferences.old_thread_threshold'), 0);
        $cutoff = $time - $age;

        // Get list of read threads for the user
        $read = DB::table('forum_threads_read')
                    ->where('user_id', '=', \Auth::id())
                    ->where('updated_at', '>=', date('Y-m-d H:i:s', $cutoff))
                    ->pluck('updated_at', 'thread_id');

        $new = DB::table('forum_threads')
                    ->whereNotIn('id', $read)
                    ->where('updated_at', '>', date('Y-m-d H:i:s', $cutoff))
                    ->where('category_id', '=', $this->id)
                    ->pluck('updated_at', 'id');


        $unread = 0;

        foreach($new as $key => $thread) {
            if(array_key_exists($key, $read)) {
                if($new[$key] > $read[$key]) {
                    $unread++;
                }
            } else {
                $unread++;
            }
        }

        return $unread;

    }
```

I'm still reasonably sure there's a single query that will do it without any post processing, but this is working for us without any issues and little overhead for the 9 forum categories we have.
