### ISSUE TITLE
Add /modify a function in contoller file 

### ISSUE THREAD

**Issue by ulshamim** [Riari/laravel-forum#118]
How can add/ modify a controller file with out editing the original controller file from vendor.

**Comment by Riari** [comment]
Controllers in this package (i.e. the API ones) aren't extendable at the moment. Some upcoming changes to routing might enable you to specify your own controllers, but it's not possible currently unless you want to disable the package routes and write your own (effectively only using the models). Not keen on the idea anyway as I don't believe the API should be modifiable.

Front-end controllers can be extended in your app - just change the controller namespaces in the `forum.frontend.controllers` config.
