### ISSUE TITLE
nested sub-categories 

### ISSUE THREAD

**Issue by morloderex** [Riari/laravel-forum#119]
Hello :) 

While using this package i noticed that everytime i retrieved my categories collection while eager loading it's children's sub categories. The children's doesn't really get eager loaded and we end up with the tipical 1 +x n problem. If we loop through each child categories. 

How can we avoid this?

**Comment by Gummibeer** [comment]
By doing things like:

``` php
$category->load('children');
$categories = $this->api('category.index')
            ->parameters(['with' => ['children']])
            ->get();
$category = Category::with('children')->find(1);
```

It have to be done in the Controller and not the Model with the `$with` attribute cause in this case it will run in an endless stack of loop and recursiv function calls and this will be end with an 500 error.
