### ISSUE TITLE
max-nesting

### ISSUE THREAD

**Issue by luarcito** [Riari/laravel-forum#121]
Hi!,
I can't work it.
![captura345](https://cloud.githubusercontent.com/assets/15383661/13724986/07234e26-e896-11e5-9e95-cfba660e4956.JPG)

**Comment by Riari** [comment]
Not sure if you're still interested in solving this or if you solved it already, but the max_nesting_level value you're showing is obviously not the one being used by PHP. It must be coming from somewhere else. You'd need to verify which php.ini file is being loaded and see if the xdebug config is being overridden anywhere.
