### ISSUE TITLE
Changing the default Forum Policy

### ISSUE THREAD

**Issue by JoeDMitchell** [Riari/laravel-forum#124]
Hi all,

I am working on the policies and I have the Category, Thread and Post Policy overrides working great however the Forum Policy isn't getting overwritten and is just reverting to the vendor one. Here is my forum.integration file

```
'policies' => [
        'forum' => App\Policies\UserForumPolicy::class,
        'model' => [
            Riari\Forum\Models\Category::class  => App\Policies\CategoryPolicy::class,
            Riari\Forum\Models\Thread::class    => App\Policies\ThreadPolicy::class,
            Riari\Forum\Models\Post::class      => App\Policies\PostPolicy::class
        ]
    ],
```

**Comment by Riari** [comment]
Are you still having this issue? I know it works in the demo, so it seems like a problem with your setup.

**Comment by maximusblade** [comment]
im having issues with this too.
ThreadPolicy does not seem to be over written.

**Comment by Riari** [comment]
I'm using this in production now and policy overriding works for me:

https://github.com/Riari/rna-guild.net/blob/master/config/forum.integration.php
https://github.com/Riari/rna-guild.net/tree/master/app/Policies/Forum

**Comment by maximusblade** [comment]
I think it was my mistake.
I renamed my class files and it worked.
This forum is fantastic. _thumbs up_
