### ISSUE TITLE
Redirect when trying to access private category instead of error

### ISSUE THREAD

**Issue by mydnic** [Riari/laravel-forum#130]
Hello

When a category is private and you try to access it by the URL as a guest user, it throws an error.
It would be great to redirect to the forum home page with an error message.

It's actually a problem because in my application I send an email to all users that have participated to a forum post. And in this email I include a link to the post so the users can go and see the new message. But if these users are not automatically logged in, and thus arrive on the page as guest user, they receive a 500 error.

Thank you for considering this !

Regards

**Comment by Riari** [comment]
Hey,

Viewing a private category as a guest shouldn't result in a 500, it should return a 403 (as per Laravel's default behaviour). Can you provide more detail, maybe a stack trace?

Thanks

**Comment by mydnic** [comment]
Seems like I've an error inside an error
http://i.imgur.com/N3aGKPR.png

**Comment by Riari** [comment]
I think I see the problem. The API internally is returning a 403 as expected, but the controller receiving it isn't handling it correctly. Are you using the standard frontend? (Edit: nevermind, I can see from the error that you are!) 
Try modifying the [`BaseController::handleResponse()`](https://github.com/Riari/laravel-forum-frontend/blob/1.0/src/Http/Controllers/BaseController.php#L52) method to do an `abort(403)` if it receives a 403.

**Comment by mydnic** [comment]
Cool! I was able to add a condition and redirect if it receives a 403, but I'm not sure how do I pass the error message ?
Also, is there a way to override that somewhere so the changes won't be lost once the package is updated ?

**Comment by Riari** [comment]
I'll apply it in the package as a fix :) though if you wanted to customise it from your app source instead, you could extend the frontend controllers and change the namespace/controller class names in https://github.com/Riari/laravel-forum-frontend/blob/1.0/config/frontend.php. But that's probably more effort than it's worth.

As for customising 403s, you can change your `app/Exceptions/Handler.php` to return a given view. See https://mattstauffer.co/blog/laravel-5.0-custom-error-pages (works for the latest Laravel versions too).

**Comment by mydnic** [comment]
Thanks for the tips :)
I'll wait for your fix then ! Thanks a lot for your reactivity !

**Comment by Riari** [comment]
Fixed in frontend version [1.0.4](https://github.com/Riari/laravel-forum-frontend/releases/tag/1.0.4) :)
