### ISSUE TITLE
Change type hinting in policies to enable use of models in the app namespace

### ISSUE THREAD

**Issue by Riari** [Riari/laravel-forum#131]

**Comment by maximusblade** [comment]
i think this change may be having an influence in my setup?
could it be causing this kind of error ?

**Comment by Riari** [comment]
If you try to pass your own models to the policies and type hint those instead of the package ones in your overridden policies, you'll get an exception. I'm not sure what to do with this yet, but if you aren't getting an exception then it's unrelated.
