### ISSUE TITLE
Latest release is breaking

### ISSUE THREAD

**Issue by mydnic** [Riari/laravel-forum#133]
Hello @Riari 
I just wanted to warn that because of the 3.0.5 release and the "Removes route attributes from models" change, an update can break an application.
I believe that a release number that increases only the 3rd number is only for minor and non-breaking updates.
Anyone that is not that careful (on github feed or on package release notes) and that runs a composer update command on a production environment can break an entire app because of a 500 error

Now, I personally got the error while working on my locale machine but I still needed to go to your repo page and search why it suddenly broke. I was using the getLastPostUrlAttribute() method so now I know that I have to update the package :smile: 

I guess some people might not directly see where the error is coming from if they were using it as well.

Anyway I just wanted to point that it might be a breaking change for some people.

Keep up the good work

**Comment by Riari** [comment]
Edit: disregard my previous comment. I just realised you're suggesting the release should have been 3.1.0 instead of 3.0.5, in which case, you're totally right. Not sure what I was thinking. Fortunately I think I can remove the release and tag and create it again as 3.1.0 without causing any problems for anyone else. I'll look into that in a moment.

**Comment by Riari** [comment]
Done - 3.1.0 and frontend 1.1.0 are the new side by side releases, although it's not going to help in Composer terms since "~3.0" and "~1.0" will still pull these versions in, but at least it's more accurate now. If you have any other suggestions, let me know :) thanks!

**Comment by mydnic** [comment]
Thanks for your reactivity ! That's good I guess! I'm closing this then.
We will see if people complain anyway, I suppose :smiley:
