### ISSUE TITLE
Translating Attributes on Validation

### ISSUE THREAD

**Issue by m3rg** [Riari/laravel-forum#136]
Is there a way to translate the attribute names when validating the request maybe other than overriding the controller?
Example: content is required. Required entry is defined as `The :attribute field is required.` in validation language file. How can I also translate this attribute?
Thanks.

**Comment by Riari** [comment]
You can override attribute names in https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L112 - I'll see if there's a clean way of providing translations for them out of the box in a future release, but for now, that's your best option I think.
