### ISSUE TITLE
Can Delete

### ISSUE THREAD

**Issue by kinnedev** [Riari/laravel-forum#140]
Where can I find that functionality for the @can ('delete', $category)?

Looks like all the auth users are able to delete all categories and I am trying to only allow auth users to delete there own threads

**Comment by Riari** [comment]
The readme covers this in basic terms: https://github.com/Riari/laravel-forum#policies-user-permissions

For more info, see http://teamteatime.net/docs/laravel-forum/3.x/policies.md
