### ISSUE TITLE
Is there any way of fire an event on thread store function

### ISSUE THREAD

**Issue by aenciso** [Riari/laravel-forum#141]
From the documentation I can see that an event is fired on UserCreatingThread but I'd like to fire an event after thread is created, maybe on created method in PostObserver.

What is the best practice to add/extend this feature?

Thanks

**Comment by Gummibeer** [comment]
I think you can use the standard eloquent events!? https://laravel.com/docs/5.1/eloquent#events

**Comment by Riari** [comment]
That would be one way of doing it, but unfortunately it's currently not possible to override the models throughout the package, only for policies - so you'll have to create your own observer class for the Thread model and register it in one of your app's service providers.

Edit: that might be overkill if you only want to register a single event of course - you have the option of reacting to an event directly from a service provider's `boot` method: https://laravel.com/docs/5.2/eloquent#events

**Comment by aenciso** [comment]
That's what I thought. I can listen to an event directly but the event must be triggered by the action inside the package right?

UserCreatingThread is useful for online assistance for example, but it would be a nice enhancement if another event is fired afterwards, something like UserCreatedThread so another functionality can react when a user posts a thread, maybe a bot or a filter to remove unwanted words, a broadcast to all involved users, etc...

**Comment by Gummibeer** [comment]
@Riari and my solution as code:

``` php
<?php
namespace App\Providers;
use Illuminate\Support\ServiceProvider;
use Riari\Forum\Models\Thread;
class ObserverServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Thread::created(function(Thread $thread) {
            // your logic what you want to do with the thread after it was created
            /*
            something like:
            notify_users('thread_created', $thread->readers, $thread);
            filter_posts($thread->posts);
            // and so on
            */
        });
    }
}
```

The same would be possible with all the other Models.

**Comment by Riari** [comment]
I wrote the events in the package to cover scenarios that Eloquent doesn't handle, since it can't determine when a user is about to create/update/delete a model, only during or after. So you can register an Eloquent event and it will get fired automatically by Laravel whenever the package calls the relevant Eloquent methods. :)

**Comment by Riari** [comment]
@Gummibeer sorry, yeah, for some reason I was thinking of registering events in the models themselves when I read your reply. I somehow neglected to consider they're the same thing :)

**Comment by aenciso** [comment]
@Riari You're right. Didn't check the models properly. Thanks.

@Gummibeer Thanks. Nice and simple!
