### ISSUE TITLE
Store post count against forum and thread

### ISSUE THREAD

**Issue by unbolt** [Riari/laravel-forum#142]
As discussed in [this](https://github.com/Riari/laravel-forum/issues/139) issue.

I'll work on this and provide my code, I'll also make an artisan command to update the values.

**Comment by unbolt** [comment]
This is about 90% done now, and it is SO much faster on my system. My forum index is on about 175 queries instead of 4k, which is a vast improvement.

Just need to get the figures updating when posts are made now.

**Comment by unbolt** [comment]
I've attached my code completely, hopefully you can do a diff on it or something to find out exactly what I have changed. Mostly in ThreadObserver and PostObserver as suggested, but I removed a bit and changed the views in the frontend.

[riari.zip](https://github.com/Riari/laravel-forum/files/355619/riari.zip)

**Comment by unbolt** [comment]
My artisan command needs a little work so not currently included. I just noticed that it updated all the modified dates when I ran it so all the forum posts are now in incorrect order :D

**Comment by unbolt** [comment]
Further updates required, it's not my artisan command that caused that, need to disable timestamps when updating post counts. To be continued.

**Comment by Riari** [comment]
Good progress; thanks a lot for sharing your code. I'll wait for more before I look at merging your changes in. :)

**Comment by unbolt** [comment]
It works!

It does not account for moving threads, so would need to run the artisan command if you did that to recount all the forums properly, which is a bit awkward. It's a start though.

[riari.zip](https://github.com/Riari/laravel-forum/files/355680/riari.zip)

And here is my refresh command, I don't know how to integrate it.

[UpdatePostCounts.php.zip](https://github.com/Riari/laravel-forum/files/355684/UpdatePostCounts.php.zip)

**Comment by Riari** [comment]
OK, I've pushed a commit that includes your changes. I had to adapt the observers to cover all scenarios (especially where soft deletion is concerned). Thanks a lot for your work!
