### ISSUE TITLE
[2.*] Index route does not have a name.

### ISSUE THREAD

**Issue by nCrazed** [Riari/laravel-forum#143]
While every other route in the `2.*` version has a name like `"forum.{$method}.{$routeName}"`, the route for `ForumController@getViewIndex` does not. This requires special handling when creating links to this route.

I see that the structure is completely changed for the `3.*` branch so it's no longer applicable there, but `2.*` could still use an improvement here. 

I am happy to submit a PR if you're still taking them for the `2.*` branches.

**Comment by Riari** [comment]
Sorry for the late reply. A PR would be welcome, thank you :)

**Comment by nCrazed** [comment]
Do you have anything that keeps the L4 and L5 variants in sync?

**Comment by Riari** [comment]
Nope.
