### ISSUE TITLE
Carbon Locale not set

### ISSUE THREAD

**Issue by Nalem14** [Riari/laravel-forum#145]
Hello :-)

I have seen the Carbon locale was not set.
I suggest to add them relative to the `App::GetLocale`

`Carbon\Carbon::setLocale(\App::getLocale());`

Thanks, have a good day,
Thommy

**Comment by Riari** [comment]
I think this ought to be handled at the application level, but it's a trivial change so I've included it in the latest release regardless. Thanks.
