### ISSUE TITLE
Cannot run PHP migrate

### ISSUE THREAD

**Issue by KDA809** [Riari/laravel-forum#148]
when i try running php migrate i get the error 

```
←[37;41m                                                                               ←[39;49m
←[37;41m  [Doctrine\DBAL\Schema\SchemaException]                                       ←[39;49m
←[37;41m  There is no column with name 'parent_category' on table 'forum_categories'.  ←[39;49m
←[37;41m                                                                               ←[39;49m
```

**Comment by Riari** [comment]
Is this on a fresh install? I can't see any reason why this would happen unless the table was modified in between package updates. The column is created in one migration and then renamed in a newer one:

<img width="583" alt="screen shot 2016-09-19 at 10 30 22" src="https://cloud.githubusercontent.com/assets/3583774/18627681/21a6e02e-7e54-11e6-990b-1f9045760026.png">

**Comment by KDA809** [comment]
fresh install bud changed nothing but followed instructions

**Comment by KDA809** [comment]
sorted

**Comment by Riari** [comment]
What was the problem?

**Comment by KDA809** [comment]
Unsure it seems to be with My work machine as i tried this on that and its got proxys allsorts so was playing hard to get i just manually added sorted it strange but working lol
