### ISSUE TITLE
My users table have first_name and last_name for name.

### ISSUE THREAD

**Issue by kanamania** [Riari/laravel-forum#15]
You specified in the forum.integration file that you point only one column from user model to be name. How can I use the first name and last name in there.???

**Comment by Riari** [comment]
Create a new attribute like this on your user model:

``` php
public function getFullNameAttribute()
{
    return "{$this->first_name} {$this->last_name}";
}
```

Then you can change the `forum.integration.user_name_attribute` value to `fullName`.

**Comment by kanamania** [comment]
thanks for this
