### ISSUE TITLE
riari/laravel-forum-frontend 1.1.4 requires riari/laravel-forum ~3.0

### ISSUE THREAD

**Issue by barak-haviv** [Riari/laravel-forum#151]
The frontend works only for the forum version ~3.0
Is there any way to manage laravel 5.3 to work with it ?

**Comment by Riari** [comment]
Sorry, I overlooked this. Fixed in new release: https://github.com/Riari/laravel-forum-frontend/releases/tag/1.1.5

**Comment by barak-haviv** [comment]
Thanks.
This seems to work
composer require riari/laravel-forum-frontend:~1.1.5
you might want to consider to fix the installer guide

**Comment by Riari** [comment]
There's no need to specify the exact version. The readme and docs says to use `composer require riari/laravel-forum-frontend:~1.0`, which will pull in 1.1.5.

**Comment by barak-haviv** [comment]
I got my error after running this
composer require riari/laravel-forum-frontend:~1.0

so I checked it again remove and install
and now it works.
so I am closing it

**Comment by Riari** [comment]
That's because you ran it when 1.1.4 was still the latest version. A `composer update` would have bumped it up to `1.1.5` in your composer.lock. Glad it's working for you now anyway :)

**Comment by barak-haviv** [comment]
OK I see 
thanks for update
