### ISSUE TITLE
Implement Baum

### ISSUE THREAD

**Issue by breakeryouko** [Riari/laravel-forum#158]
What do you think to implement Baum as nested set pattern?
https://github.com/etrepat/baum

**Comment by Riari** [comment]
This is planned for [illuminate-forum](https://github.com/Team-Tea-Time/illuminate-forum) when I get a chance to work on that properly. Doubt I'll invest the time to bring it to this package as I plan to provide an upgrade path to illuminate-forum when the time comes. 👍
