### ISSUE TITLE
How about threads views?

### ISSUE THREAD

**Issue by kanamania** [Riari/laravel-forum#16]
Is there a way to support thread views and show them in the forum > category listing.?

**Comment by Riari** [comment]
The category view already displays a list of threads - what exactly do you want to do apart from that? Show X posts from the latest thread, something else?

**Comment by kanamania** [comment]
I mean views as VIEWS. the number of people viewed a thread.

**Comment by Riari** [comment]
Oh, sorry! In that case, it's not possible at the moment. I'm thinking about adding it for a future release as an extension of the read/unread tracking.

Until then, if you really need this functionality, you might be able to achieve it with a combination of a custom table to track the view counts, [Model Event](http://laravel.com/docs/5.0/eloquent#model-events) handlers on the ForumThread model and a [View Composer](http://laravel.com/docs/5.0/views#view-composers) (or View::share).

**Comment by Riari** [comment]
Hi there,

~~Just in case you're interested, the [latest release](https://github.com/Riari/laravel-forum/releases/tag/2.3.7) introduces thread view count support. It will only count views from logged in users, but you might still find it useful.~~

Edit: scratch that, I think I might actually implement it differently - sorry. I've taken the new releases down for now, but keep an eye out for updates if interested.

Thanks

**Comment by Riari** [comment]
Re-implemented in [2.3.8](https://github.com/Riari/laravel-forum/releases/tag/2.3.8).
