### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by stormhillmedia** [Riari/laravel-forum#166]
1. Added the package per instructions
2. went to /forum (could use some documentation on if this is the correct homepage -- had to find in routes)

3. got error:

Invalid argument supplied for foreach() (View: /home/vagrant/Code/d3iproject/resources/views/vendor/forum/category/partials/options.blade.php) (View: /home/vagrant/Code/d3iproject/resources/views/vendor/forum/category/partials/options.blade.php) (View: /home/vagrant/Code/d3iproject/resources/views/vendor/forum/category/partials/options.blade.php)

**Comment by scalderdom** [comment]
Maybe you try use 3.0 version of package on laravel 5.3 or above. I get this error, when try 3.0 version on laravel 5.4.
