### ISSUE TITLE
Route not found NotFoundHttpException in RouteCollection.php line 161

### ISSUE THREAD

**Issue by dmhamilt** [Riari/laravel-forum#168]
Good afternoon, 

I have installed this on a  Windows/Vagrant virtual server and Digital Ocean Server. The Digital Ocean server is working fine, but my local virtual server has a route issue.

NotFoundHttpException in RouteCollection.php line 161.

I have reinstalled and reloaded the virtual server but nothing seems to work. Any ideas?

**Comment by breakeryouko** [comment]
Did you change the default route?

**Comment by dmhamilt** [comment]
no . Do I need to?

I ran "php artisan route:list" and noticed  my local virtual server does not have any Riari routes listed

**Comment by dmhamilt** [comment]
I dumped the config cache and it cleared it up.  
php artisan config:clear
