### ISSUE TITLE
Prevent moving a category to a child of itself

### ISSUE THREAD

**Issue by Riari** [Riari/laravel-forum#171]

**Comment by hardiktailored** [comment]
I am trying to prevent listing child categories of currently selected category using with and conditions but it only works for two levels and on third level its not working, I think it has issue with relation and condition, can you advice?

    $category = $this->api('category.fetch', $request->route('category'))->get();
    
    $categories = $this->api('category.index')->parameters(

                            ['where' => [
                                            ['id', '<>', $category->id],
                                            ['category_id','!=', $category->id],
                                            ['category_id', 0]
                                        ],
                            'orderBy' => 'weight',
                            'orderDir' => 'asc',
                            'with' => ['categories' => function ($query) use ($category) {
                                        $query->where(
                                                        [
                                                            ['id', '<>', $category->id],
                                                            ['category_id','!=', $category->id]
                                                        ]
                                                    );
                                        }
                                        , 'threads'
                                    ],
                            ])
                           ->get();

**Comment by Riari** [comment]
Nothing to do with this issue. Please create a new one.

**Comment by hardiktailored** [comment]
Anyways, I just fixed issue with adding one more condition `$cat->id != $category->id` in category loop of file forum/category/partials/options.blade.php (different with your version as I have created a edit category form)

My final file looks

    @foreach ($categories as $cat)
    @if ((!isset($hide) || (isset($hide) && $cat->id != $hide->id)) && $cat->id != $category->id)
    	@if (isset($edit) && $edit == true)
    		<option value="{{ $cat->id }}" {{ (isset($category) && $cat->id == $category->category_id) ? 'selected' : '' }}>
    	@else
    		<option value="{{ $cat->id }}" {{ (isset($category) && $cat->id == $category->id) ? 'selected' : '' }}>
    	@endif
        
            @for ($i = 0; $i < $cat->depth; $i++)- @endfor
            {{ $cat->title }}
        </option>
    @endif

    @if ($cat->children && $cat->id != $category->id)
        @include ('forum::category.partials.options', ['categories' => $cat->children])
    @endif
    @endforeach

**Comment by hardiktailored** [comment]
Suggestion: you can add one parameter while listing category for move actions to get select current parent category:

Replace `@include ('forum::category.partials.actions')` with `@include ('forum::category.partials.actions', ['edit' => true])`

**Comment by Riari** [comment]
I'm going to delete your replies since you seem to have no regard for what I just asked.
