### ISSUE TITLE
Controller method not found.

### ISSUE THREAD

**Issue by nijesh-wiredelta** [Riari/laravel-forum#176]
I'm using laravel 5.1 and my forum is "riari/laravel-forum": "~3.0" and  "riari/laravel-forum-frontend": "~1.0".
When i go to http://localhost/consensus/tryccc/public/forum getting (NotFoundHttpException in Controller.php line 269: Controller method not found.) error.

**Comment by Riari** [comment]
Closing this as it looks to be a project env/config issue rather than a bug.
