### ISSUE TITLE
[Showcase] Forum Design

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#18]
here are some screenshots of what the forum looks like:
I still have to work on the thread list.

Posts
![Post](http://i.imgur.com/yoZ6c77.png)

Front Page
![Front Page](http://i.imgur.com/HbwITaV.png)

Quick Menu
![Quick Menu](http://i.imgur.com/AoQK9n4.png)

**Comment by Riari** [comment]
Thanks for sharing these, I'll add a new Showcase page to the wiki soon. Do you want me to include the URL?

Feel free to add any more screenshots in the meantime when you make progress with your design.

**Comment by Denoder** [comment]
yes you can include it.
url: animezero.tv

still thinking of things to add so if u can suggest something feel free

**Comment by Riari** [comment]
Added: https://github.com/Riari/laravel-forum/wiki/Showcase
