### ISSUE TITLE
Not getting logged in through Sentinel

### ISSUE THREAD

**Issue by nijeshw** [Riari/laravel-forum#180]
![image](https://user-images.githubusercontent.com/2499917/29176856-abc3ab6e-7e0a-11e7-804a-9e188a0ff605.png)
My laravel version : "laravel/framework": "5.4.*",
My forum pack : "riari/laravel-forum": "~4.0",        "riari/laravel-forum-frontend": "~1.0"
please check the above screenshot

**Comment by ITwrx** [comment]
this package expects that you use the built in laravel authorization features, not Sentinel. If you choose to use Sentinel instead, then you should expect to figure out how to do that yourself, imho. I don't speak for this package maintainer. I'm just a user like you trying to explain why your current situation is not working.

**Comment by Riari** [comment]
@ITwrx is correct. I've never used Sentinel - if it uses its own auth mechanism instead of Laravel's, then it's unlikely to work without some heavy tweaking. Sorry!
