### ISSUE TITLE
Softdeleting threads permadeletes posts

### ISSUE THREAD

**Issue by TiagoLisboa** [Riari/laravel-forum#181]
Hello,
When I execute a softedelete on a thread it's posts are removed from the database.

My laravel version is: "laravel/framework": "5.5.*",
My forum pack is: "riari/laravel-forum": "~4.0", "riari/laravel-forum-frontend": "~1.0"

**Comment by TiagoLisboa** [comment]
So, i digged around for awhile and finded out that the problem is basically here:

![captura de tela de 2017-09-02 13-10-24](https://user-images.githubusercontent.com/6991359/29997048-6f79a23e-8fe0-11e7-9a64-9a5b2ab931d6.png)

![captura de tela de 2017-09-02 13-14-00](https://user-images.githubusercontent.com/6991359/29997062-a18247d6-8fe0-11e7-80bb-d35bea09e31d.png)

Because of some milleseconds the comparision goes false and the posts are hard deleted.

**Comment by Riari** [comment]
Ah, I wonder if this is unique to a newer version of Carbon - when I first wrote that condition, milliseconds weren't counted.

It's not a very reliable way of checking for hard deletion, but I couldn't easily find any better alternatives at the time. As a fix in the meantime, I could change the timestamps to format them minus the milliseconds - that should work except for the rare edge case where the time ticks over to the next second mid-deletion.

**Comment by TiagoLisboa** [comment]
Hey, just saw that when a hard delete is made the _thread_ in the _deleted_ function is _null_, causing an Error.
Instead of checking the date, you should check if it is null.
