### ISSUE TITLE
laravel 5.4 throw new ValidationException issue

### ISSUE THREAD

**Issue by oskarbet** [Riari/laravel-forum#186]
When I create thread with empty title I receive next mistake: 
FatalThrowableError
Type error: Argument 2 passed to Riari\Forum\Frontend\Http\Controllers\BaseController::handleResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in ..\vendor\riari\laravel-forum\src\API\Dispatcher.php on line 135.

**Comment by mubashir09** [comment]
test

**Comment by mushi-iqbal** [comment]
This package has many bugs.

**Comment by Riari** [comment]
@mubashir09 Instead of making a useless comment like that, you could report any bugs you know of. That would be infinitely more useful to myself and others. Thanks. 👍

**Comment by medic917** [comment]
Any chance you could tell us when the fixes will be addressed Riari? There are a few critical bugs that haven't been addressed yet and was wondering if they will be fixed or not.

**Comment by Gummibeer** [comment]
@medic917 it's open source so there isn't just one maintainer everyone can fix things and help to make this better!

**Comment by Riari** [comment]
That and the demo is out of date, so it may well have issues that aren't present in the latest release. I intend to update it with a fresh install of Laravel (and identify/verify any remaining issues in the process), but I'm very busy these days with a couple of contracts so it's not easy to find the time.

**Comment by medic917** [comment]
Ok, thank you for not abandoning the project. Hopefully we can have more people involved!
