### ISSUE TITLE
[Support] Integrating Laravel Boilerlate + Forum

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#19]
I'm basically trying to integrate the roles with the forum. What i mean is like in my example below i am able to grab the user's name and avatar or anything else that can be grabbed from the users table.
![Example](http://i.imgur.com/yiTWEE4.png)

What I need to do is grab the user's role and display it with the name that way it can specif if the user is an administrator or member or moderator etc.

could you assist me with this? 

Laravel Boilerplate: https://github.com/rappasoft/laravel-5-boilerplate

**Comment by Denoder** [comment]
I figured it out :D

**Comment by Riari** [comment]
Glad you figured it out. Could you maybe share any useful info here in case someone else has the same difficulty using Laravel 5 Boilerplate?

**Comment by Denoder** [comment]
all i did was place:

```
    /**
     * The roles that belong to the user.
     */
    public function roles()
    {
        return $this->belongsToMany('Role', config('access.assigned_roles_table'), 'user_id', 'role_id');
    }
```

in the User.php Model file.

That way i can grab it via:

$post->author->roles

Gonna have to tell rappasoft this too, to add it when he gets time.
