### ISSUE TITLE
Search feature ?

### ISSUE THREAD

**Issue by froid24** [Riari/laravel-forum#191]
No Search feature? When the number of categories/threads/posts increases, this is a necessary feature... Otherwise finding something in a huge collection of posts might be too difficult...

Thanks.

**Comment by Gummibeer** [comment]
Search is too specific and there are a lot of packages out there that add search to eloquent models.
* https://github.com/laravel/scout
* https://github.com/nicolaslopezj/searchable

I don't want this package to mess with something that depends a lot on the used software (DB, Cache, Elastic etc) and a duplicates possible already existant search-service.

**Comment by Riari** [comment]
Exactly as Gummibeer said, the scope of this package is quite strict and doesn't include features that could arguably be implemented across an entire app instead of just the forums. That extends to things like WYSIWYG editors and attachments as well.
