### ISSUE TITLE
Feature question.

### ISSUE THREAD

**Issue by medic917** [Riari/laravel-forum#193]
For disabling threads under categories, is there a reason why we can't use the function when threads are already created under the category?

**Comment by Gummibeer** [comment]
@medic917 you mean this?
https://github.com/Riari/laravel-forum/blob/86164031936447a34d3f86ab3c30ebf12b580429/src/Http/Controllers/API/CategoryController.php#L151-L160

So far I see there is no reason - it's only used here:
https://github.com/Riari/laravel-forum/blob/638a68318f9cbc42dad66833615a4ed26f25181b/src/Http/Controllers/API/ThreadController.php#L95-L97

**Comment by medic917** [comment]
Thanks for this Gummibeer!
Perhaps Riari can change enabled to default, since I don't see why disabling threads won't work when the category already has threads.
