### ISSUE TITLE
In QuestionHelper.php line 53:                        Undefined index:

### ISSUE THREAD

**Issue by yaroshaa** [Riari/laravel-forum#199]
Laravel 5.6
php 7.2
OS - Linux Ubuntu 18
xampp 

after php artisan vendor:publish, issues

" In QuestionHelper.php line 53:                    
  Undefined index:  
Process finished with exit code 1 at 15:34:56.
Execution time: 133 ms. "

all copied by hand

"invalid argument supplied for foreach() (View: /home/alexey/web/iottest/resources/views/vendor/forum/category/partials/options.blade.php) (View: /home/alexey/web/iottest/resources/views/vendor/forum/category/partials/options.blade.php) (View: /home/alexey/web/iottest/resources/views/vendor/forum/category/partials/options.blade.php) "

**Comment by Riari** [comment]
Hi,

The QuestionHelper.php error is unrelated to this package as there is no such file in it.

For the `invalid argument supplied for foreach()` error, can you provide more detail about your setup? Have you defined categories already? Have you modified any of the forum views?

Thanks

**Comment by yaroshaa** [comment]
Thanks for the answer, the settings did not change, I created a test category directly in the database, I did not change the view

**Comment by yaroshaa** [comment]
deployed the latest version of the framework, added the latest version of the forum and the latest version of the frontend for the forum. I did everything according to the order, I gave an error on the instructions

**Comment by yaroshaa** [comment]
> /opt/lampp/bin/php /home/alexey/web/iottest2/artisan vendor:publish

   ErrorException  : Undefined index: 

  at /home/alexey/web/iottest2/vendor/symfony/console/Helper/QuestionHelper.php:52
    48|         if (!$input->isInteractive()) {
    49|             if ($question instanceof ChoiceQuestion) {
    50|                 $choices = $question->getChoices();
    51| 
  > 52|                 return $choices[$question->getDefault()];
    53|             }
    54| 
    55|             return $question->getDefault();
    56|         }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: ", "/home/alexey/web/iottest2/vendor/symfony/console/Helper/QuestionHelper.php", [Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion)])
      /home/alexey/web/iottest2/vendor/symfony/console/Helper/QuestionHelper.php:52

  2   Symfony\Component\Console\Helper\QuestionHelper::ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion))
      /home/alexey/web/iottest2/vendor/symfony/console/Style/SymfonyStyle.php:294

  Please use the argument -v to see more details.

Process finished with exit code 1 at 17:45:29.
Execution time: 129 ms.

**Comment by yaroshaa** [comment]
Maybe there is a problem with access to directories?

**Comment by yaroshaa** [comment]
Sorry for my english

**Comment by Riari** [comment]
Thanks for the info. The errors you gave [here](https://github.com/Riari/laravel-forum/issues/199#issuecomment-424374584) are unrelated to this package. If they're the only errors you see, the problem lies in your own code or comes from another package. The only error related to laravel-forum is this one:

```
invalid argument supplied for foreach() (View: /home/alexey/web/iottest/resources/views/vendor/forum/category/partials/options.blade.php) (View: /home/alexey/web/iottest/resources/views/vendor/forum/category/partials/options.blade.php) (View: /home/alexey/web/iottest/resources/views/vendor/forum/category/partials/options.blade.php)
```

If you still see that, I'll have to do some manual testing to figure out what's causing it.

**Comment by yaroshaa** [comment]
Hello. Thank you for your reply. I found the cause of the error when publishing the package files. I want to share with you that in the future you could tell the users of your package how to fix the problem. Publication errors occurred when using the console, rather than a full-time terminal. Perhaps the developers of the framework missed something. Sorry for my english. Good luck.

**Comment by Riari** [comment]
Thanks for your input 🙂
