### ISSUE TITLE
Attached files on the forum

### ISSUE THREAD

**Issue by roman-yakimkin** [Riari/laravel-forum#202]
Could you clarify, is it possible to attach any files to forum topics and messages?

**Comment by Riari** [comment]
Hi,

This isn't a feature available out of the box, but you could integrate a package such as [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary) or [teamteatime/laravel-filer](https://github.com/Team-Tea-Time/laravel-filer) by extending the forum thread/post models and, if you're using laravel-forum-frontend, overriding the frontend controllers and views.
