### ISSUE TITLE
n+1 problem

### ISSUE THREAD

**Issue by silverbrick** [Riari/laravel-forum#203]
it is running multiple duplicate query 
`https://trello-attachments.s3.amazonaws.com/5997144681403f5907b99130/5bc4f68f4ef2be84a7a9e718/57da4712e19d96f95de7f162781ab497/Screenshot_from_2018-10-15_23-37-40.png`
screenshot has been added

**Comment by Riari** [comment]
Improved for version 5 (see #265).
