### ISSUE TITLE
Extending Models

### ISSUE THREAD

**Issue by joaopmarquesini** [Riari/laravel-forum#206]
Hi Riari, I'm trying to implement a custom Post model with some mutators but I'm unable to find where I can point to my custom model in the configs.
Is this possible? Or should I be doing this another way ?
Thanks!

**Comment by Riari** [comment]
It's not possible to override them per se; the most you can do is change the models referenced in the [integration config](https://github.com/Riari/laravel-forum/blob/4.0/config/integration.php) for policies and users.

You can of course extend and use them in your app namespace, but if you want to override model usage in the forum controllers, you'll have to override the controllers too.

**Comment by Gummibeer** [comment]
Is it planned to change this?

**Comment by joaopmarquesini** [comment]
Thanks Riari.
What I'm trying to achieve is simply running a strip_tags before saving the
comment to enforce content policy.
Is there a more appropriate place that I should be placing this instead of
extending the model setCommentAttribute ?

Em sex, 16 de nov de 2018 20:41, Rick Mann <notifications@github.com
escreveu:

**Comment by Riari** [comment]
@Gummibeer probably, yeah. I'll look into it for v5 🙂 

@marquesinijatinha you could try using the `creating` and `updating` Eloquent events to change the attribute just before an insert/update takes place.

**Comment by joaopmarquesini** [comment]
Hmmm good idea, I will check how that works.
Thanks :)

Em sáb, 17 de nov de 2018 09:51, Rick Mann <notifications@github.com
escreveu:

**Comment by lurkerCha** [comment]
Hi, can we possibly update the Thread model to have tags? Or maybe we could implement multiple
category for each thread? 
if not, can we simply override the Thread model and controller to implement tagging?

**Comment by Riari** [comment]
@lurkerCha multiple categories per thread is a feature I'm considering for v5 (if I ever find the time to resume work on it), but until then, yes, it's something you can implement yourself by extending the models and overriding the frontend controllers. You'll probably need to create your own controller actions and routes to support adding/updating/removing tags on a thread.

**Comment by lurkerCha** [comment]
> @lurkerCha multiple categories per thread is a feature I'm considering for v5 (if I ever find the time to resume work on it), but until then, yes, it's something you can implement yourself by extending the models and overriding the frontend controllers. You'll probably need to create your own controller actions and routes to support adding/updating/removing tags on a thread.

Great! Thank you!
