### ISSUE TITLE
[3.x] "Replying" posts lost their parents when soft-deleting post

### ISSUE THREAD

**Issue by ChristianKarlsson86** [Riari/laravel-forum#207]
When soft-deleting a post in a thread, all threads that "replied" to that post will be "disconnected" from it. When restoring the deleted post, those posts will no longer have the original post as "parent".

I think it would be better if a "soft-deleted" comment remained as parent until it is "perma-deleted", but perhaps with its content cleared out. That way, if the post is restored in the future, the link between the two posts won't be broken.

**Comment by Riari** [comment]
Addressed for 5.0 in #258.
