### ISSUE TITLE
[Need Help] Category explode list.

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#21]
Right now im populating my forum with categories
Backend (pretty neat):
![Backend](http://i.imgur.com/46LwEaY.png)

What I want to do is have the categories split with the "," that way it's listed. This is what i have as the code:

```
@foreach ($subcategory->subcategories as $subcat)
    <a href="{!! $subcat->route !!}" title="{!! $subcat->title !!}">{!! $subcat->title !!}</a>
@endforeach
```

That basically grabs the subcategory's subcategory (this can go on forever but i only needed one more nested level) to look like this:
![frontend](http://i.imgur.com/jo1JLDb.png)

the problem i'm having is making each category split with the comma. I tried using Explode but i get an error every time.

**Comment by flamerohr** [comment]
I suggest it could use CSS, rather than HTML.

The example is from memory, since I don't remember which project I used this in:

.subcat-link:after {
content: ",";
}
.subcat-link:last-child:after {
content: "";
}

**Comment by Denoder** [comment]
thanks, that works:

```
@foreach ($subcategory->subcategories as $subcat)
    <span class="subcat-link"><a href="{!! $subcat->route !!}" title="{!! $subcat->title !!}">{!! $subcat->title !!}</a></span>
@endforeach
```

**Comment by Riari** [comment]
Yeah, I use the CSS approach for that as well. Slightly more succinct rule would be:

```
.subcat-link:not(.subcat-link:last-child):after {
    content: ", ";
}
```

**Comment by Denoder** [comment]
the next feature im trying to work on is profile cards when hovering on names <_<

**Comment by Riari** [comment]
I have a generic "AJAX cards" implementation in one of my projects, so I might be able to help with that. Though please open a separate issue if you want to go into that :P
