### ISSUE TITLE
Polls support

### ISSUE THREAD

**Issue by remontees** [Riari/laravel-forum#210]
Hello!

Could you please enable a feature to let users create their own polls in their topics.

Thanks a lot

**Comment by Riari** [comment]
Hi,

Thanks for your interest! Polls are not something I'll be adding. There are a few reasons for this:

- The philosophy of laravel-forum is to provide a stripped down feature set that you can build on yourself if you need to.
- The exact functionality of polls can differ a lot (for example, how votes are tracked). It would have to be highly configurable out of the box, and that can get messy fast, so I think it's best left to individual devs.
- Polls aren't really forum-specific; they're essentially just voting widgets that happen to be displayed above forum threads, so I don't believe it should be a feature provided by default.

I hope that makes sense and I appreciate your understanding!
