### ISSUE TITLE
When i completed installing, just show index on page forum

### ISSUE THREAD

**Issue by TaufiqZulfikar** [Riari/laravel-forum#211]
Hello, I need help with my problem, I use Laravel 5.8, and I was completed to install the Laravel forum 4x and Laravel forum frontend 1x, I followed the instruction from documentation but the result only show page index like this: (https://drive.google.com/open?id=165I8u5Ljxx06W5zuVx-47qTS8OsZuVsA), how to make the page like demo site? Must I make my own page? I add a category through the database and  I tried various ways and read the discussion forums that exist but did not find it.

Thank You

**Comment by sjoy** [comment]
> Once the package is installed, provided you are logged in, you can visit /forum and start defining your category hierarchy using the "Create category" and "Category actions" panels
