### ISSUE TITLE
Laravel 6?

### ISSUE THREAD

**Issue by jetwes** [Riari/laravel-forum#213]
Hi, 

are there any plans on supporting L6?

Kind regards
Jens

**Comment by Riari** [comment]
Hey,

I'll certainly look into it. No ETA as I've barely explored Laravel 6 and don't know the extent of breaking changes, but hopefully it'll be somewhat painless.

Chances are I'll release a new major version to coincide with L6, in which case I may take the opportunity to overhaul some stuff. I was working on a total rewrite and simply don't have time for that these days, so this might be a good compromise.

Cheers

**Comment by jetwes** [comment]
Hi Rick,

thanks for the quick reply. What i saw first is that the Input Facade is removed in 6.0 - so that have to be replaced with the Request Facade... I'm using it with 5.8 without problems at the moment. (with some optimizations on counting, queries, etc..).

other than that it should work - i think...

**Comment by XternalSoft** [comment]
Hello!

Any news ?

**Comment by Jemy09** [comment]
Hi, 
I am performing a big Laravel upgrade from a site I've taken over.
Now having the same issue when upgrading to 6.0...  Is there any work-around to replace this package as there hasn't been any upgrade for it? 
Thanks
Jerome

**Comment by Riari** [comment]
Hi,

Version 5 of this package is compatible with Laravel 6 and above. It's not ready yet, but it's close. If you need a more immediate solution, I'm afraid I can't help much there - your best bet may be to fork version 4 and make the necessary changes for Laravel 6 compatibility. Happy to answer any questions regarding that.

I'll update this issue when v5 gets a stable release.

**Comment by jetwes** [comment]
Hi Jerome,

i forked it a year ago and ported it to l6 and l7 - other than that I did nothing.
you can give it a try if you like:
https://github.com/jetwes/laravel-forum 

It's not actively maintained - but maybe it helps in your special situation...

Cheers Jens

**Comment by Jemy09** [comment]
Awesome!
Thanks so much for the quick answers and help!
I will give it a go.
cheers
Jerome

**Comment by Riari** [comment]
Hi,

V5 is coming along, but I've done a new V4 release to expand supported versions to include 6, 7, and 8 (basically what @jetwes did). Looks like the only compatibility issue was a call in the config to the `str_random()` helper, which was superseded by `Str::random()` in Laravel 5.7 onwards.

I don't intend to support V4 once V5 is out, but if anyone uses it and encounters problems, let me know!

Thanks
