### ISSUE TITLE
After category creation, all policies return true on main index page

### ISSUE THREAD

**Issue by ThePoet444** [Riari/laravel-forum#214]
So, I have an interesting bug. I'm pretty sure I'm doing something wrong but I can't fathom what. I'm using Laravel 5.8, and in my composer.json I have 
```
"riari/laravel-forum": "~4.0",
"riari/laravel-forum-frontend": "~1.0",
```

All is well. No issues installing. Go to the main forum page, I can create a category. I change the config policy to extend your forum policy, and all is well again. Change ```createCategories``` to false, I reload the forum page, can't make a new category. Perfect! revert, make a new top level category, no threads allowed called information. Make a second category called announcements that use the parent category of information. Perfect. I edit the ```createCategories```  to return ```false```. reload the forum page, the create category link is gone. go back to the forum main index page, and now I see the create category link again. Trying to submit the form gives me a 403, so at least that works. However, I'm not sure why the link is being displayed when the return is set to false. If I edit the master blade file and dd() a check like ```{{dd(Auth::user()->can('permissionDoesntExist'))}}``` This returns true. Despite that permission not existing. I'm really scratching my head here trying to figure out what's going on. I'll gladly post any code you need, I'm just not sure what. It seems like all the policies in laravel are returning true on the main forum index page, any other forum page, or site page, and they work as intended. Thanks for your time!

**Comment by Riari** [comment]
Sorry I never got around to replying to this. A new major version of the package will be released soon and I don't intend to continue supporting older versions, but if by some chance you still use the package and have any problems with it, feel free to open a new issue! Thanks.
