### ISSUE TITLE
Error on Category Add when description and title rules are removed

### ISSUE THREAD

**Issue by rsiasat00** [Riari/laravel-forum#222]
When I remove the description and title from the forum.validation file, by default I am expecting the error message on submit to just show the title field is required, but it results to this error instead:

![image](https://user-images.githubusercontent.com/31335778/78095696-2ce63200-740a-11ea-8bc9-cf68362efc75.png)

Rules array:

![image](https://user-images.githubusercontent.com/31335778/78095480-af222680-7409-11ea-86fb-633a90bc1a86.png)

Also, is there any way I can create custom messages for the rule validation?

**Comment by Riari** [comment]
Sorry I never got around to replying to this. The rules option has been removed from config in version 5 in favour of having just a few options to set the minimum title and content lengths. I don't plan to support older package versions with this new version around the corner, but I would be happy to accept a PR if anyone would like to see this specific issue fixed.

Regarding message customisation, Laravel supports that out of the box - see https://laravel.com/docs/8.x/validation#manual-customizing-the-error-messages
