### ISSUE TITLE
Multi-language diffForHumans();

### ISSUE THREAD

**Issue by breakeryouko** [Riari/laravel-forum#23]
I want to know how is it possible to change the {{ trans('forum::base.posted_at') }} {{ $post->posted }}
I can't find posted in the code but I guess you are using something like Carbon's diffForHumans() function.
I need to set it to another language.
Thanks for your help

**Comment by Riari** [comment]
Good question - I know Carbon isn't translation friendly, but you might have some luck with [jenssegers/laravel-date](https://github.com/jenssegers/laravel-date).

Edit: you also have the option of just accessing the timestamps directly (created_at and updated_at) if you want to construct/format them in other ways.

**Comment by breakeryouko** [comment]
To use it I have to set
Date::setLocale('nl');

Where can I set it?

**Comment by breakeryouko** [comment]
I found another way to do it.
In laravel 5+ you have to create a new Middleware and add

Carbon::setLocale('en');

just change en with your language.
If you put something like:

// Check for session override
if (Session::has('lang'))
{
    $local = Session::get('lang');
    Carbon::setLocale($local);

}

It's possible to give the correct language for each user.
