### ISSUE TITLE
Error when click manage menu

### ISSUE THREAD

**Issue by codebyoul** [Riari/laravel-forum#236]
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [forum.api.bulk.category.manage] not defined. (View: D:\wrk\xampp\htdocs\test\resources\views\vendor\forum\category\manage.blade.php)

**Comment by Riari** [comment]
Hi - it looks like this relates to version 5, which is currently under development. I'm also unable to replicate the error in the 5.0 branch (where the work in progress is).
