### ISSUE TITLE
To many Queries

### ISSUE THREAD

**Issue by Codename-Beast** [Riari/laravel-forum#24]
i used the Debugbar and the debugbar says the forum index alone has 62 Queries and the Threads has 48 Queries can you fix this pleas or is this normal?
![oha](https://cloud.githubusercontent.com/assets/7310030/8272904/31072534-1856-11e5-9782-280bd4b0dad8.PNG)

**Comment by Riari** [comment]
Some of those queries could probably be optimised, yes. The query count doesn't really say much by itself though - it could go into the hundreds and still be justifiable, depending on what else you're showing on that particular page (and generally speaking, many popular forum solutions are a lot more query-heavy than this).

That said, I'm currently working on refactoring the whole package with Laravel 5.1 in mind, and as part of that I'll be spending some time on optimisation. DB querying should see some improvement after that.

Edit: looking at your query log again, I can see a few queries that shouldn't be happening at all. I will investigate when I can, but have you changed the forum views at all? Not everything is eager-loaded, so calling certain model attributes in the views might result in additional queries.

**Comment by Codename-Beast** [comment]
I use the original controller and the views I have customized only the design. However the queries are the same as in the original.

Thats my Custom Design for the Forum System
![shiow](https://cloud.githubusercontent.com/assets/7310030/8273233/0992cdec-1864-11e5-9e3b-7465314f1b21.PNG)

**Comment by Riari** [comment]
Okay, that definitely bears some investigation then. Keep an eye on the [l5-refactor branch](https://github.com/Riari/laravel-forum/tree/l5-refactor) if you're interested, although the extra queries are pretty insignificant so it's not a major cause for concern.

**Comment by Codename-Beast** [comment]
Ok thanks for the quick response
