### ISSUE TITLE
Where can I find "seeding" content for demo version?

### ISSUE THREAD

**Issue by NDanilov2015** [Riari/laravel-forum#244]
Hi! Where I can find seeding files for database used in this demo-version?
https://github.com/Team-Tea-Time/laravel-forum-demo
https://laravel-forum.teamteatime.net/

I install demo version of forum, and can't know how correctly fill database tables to get similar structure.

Also I want do auth with password using, what need change for it?

Also I want enable register of new users)

**Comment by Riari** [comment]
Hi,

Sorry for the delayed reply. There's no seeder for the demo structure; if it helps, here's the SQL for inserting categories:

```sql
INSERT INTO forum_categories (category_id, title, description, weight, enable_threads, thread_count, post_count, private)
VALUES (0, 'Top-level Category', 'Contains categories', 0, 0, 0, 0, 0),
        (1, 'Subcategory 1', 'Contains threads', 1, 1, 1, 2, 0),
        (1, 'Subcategory 2', 'Contains more threads', 2, 1, 1, 2, 0);
```

When v5 is released, I'll update the demo and likely have a command and seeder for resetting the schema and inserting these categories.

Regarding auth and registration, both of those are up to you; the package is designed to work with the user auth scaffolding that comes with Laravel. The package is only concerned about where to find the user model and what middleware to apply to the routes.

Feel free to reply further or open a new issue if you have any more questions :)

Thanks
