### ISSUE TITLE
Nothing to publish

### ISSUE THREAD

**Issue by AleJuradoMarin** [Riari/laravel-forum#25]
Hi all,
I have a big problem with this, I downloaded the package,  then when i make the php artisan vendor:publish, it always return a nothing to publish and I dont know why,I make all the steps well from the wiki, hope somebody can help me :C

thanks

**Comment by Riari** [comment]
Hi,

Which version did you download, and which version of Laravel are you using?

**Comment by AleJuradoMarin** [comment]
Hi, laravel are 5.0.\* and Riari and riari/laravel-forum:~2.0.

**Comment by Riari** [comment]
I can't reproduce this. Are you sure you added the service provider (`'Riari\Forum\ForumServiceProvider'`) to your config/app.php?

**Comment by AleJuradoMarin** [comment]
Yes i added it, i'm sure, but i think is not problem of me of your package, i think its something on my laravel config

**Comment by Riari** [comment]
Sorry, I'm not really sure what to suggest other than installing the package on a fresh Laravel install so you can identify any issues with your config.

**Comment by VyacheslavVV** [comment]
I see that this is old, but I had a similar issue. The thing that helped me was - clearing config cache:
~# php artisan config:cache

**Comment by Gummibeer** [comment]
@VyacheslavVV right, but on a local machine, during development, you should never use config cache. This will be a pain to code with.
And during a deployment you should have a step which clears and caches again the config.
