### ISSUE TITLE
changing root directory for forum

### ISSUE THREAD

**Issue by djentleman** [Riari/laravel-forum#26]
Hi,

I am a bit of a Laravel noob, and I'm wondering where exactly is the routing occurring when i head to <root>/forum, as I would like  introduce a parameter into this path.

I am using Laravel 4.2

Thanks :)

**Comment by djentleman** [comment]
found it literally seconds after making this issue -.-

**Comment by Riari** [comment]
Hehe, no worries. Glad you figured it out.
