### ISSUE TITLE
How to seed?

### ISSUE THREAD

**Issue by niloc7** [Riari/laravel-forum#274]
I've tried for hours to seed the database using php artisan db:seed --class=TeamTeaTime\Forum\Database\Seeds\ForumSeeder

It always returns:  Target class [TeamTeaTime\Forum\Database\Seeds\ForumSeeder] does not exist.

The only difference is that I am using Laragon instead of a docker app.

Any pointers on what I might be doing wrongly?

**Comment by Riari** [comment]
I've noticed issues with this before and thought I had solved it. I'm not really sure why it's broken, so I'll have to investigate when I can and get back to you.

In the meantime, you should be able to copy the seeder to your own application, change the namespace, run `composer dump-autoload`, and run the seeder again with the new namespace.

**Comment by Riari** [comment]
Quick update on this. I wasn't able to figure out why artisan won't run the seeder via the namespace, but I added a `forum:seed` command in [5.2.1](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.2.1), which is now the recommended method for seeding.
