### ISSUE TITLE
Dependency error doctrine/dbal ^2.12

### ISSUE THREAD

**Issue by mdev64** [Riari/laravel-forum#276]
This package require doctrine/dbal v2*, but other packages I use locked my doctrine/dbal to v3* in composer lock. Is this not compatible with latest doctrine/dbal version? If it is compatible, please allow the installation with doctrine/dbal v3* thanks.

**Comment by Riari** [comment]
Updated in #280. I think it should be fine, but can you verify that it works for you? Thanks!

**Comment by mdev64** [comment]
Yes, it worked for me.

**Comment by Riari** [comment]
Great, thanks. I'll merge this and do a new release ASAP.
