### ISSUE TITLE
Uncaught Attempted to open modal 'delete-thread' but no such modal found.

### ISSUE THREAD

**Issue by dBaliukynas** [Riari/laravel-forum#281]
Whenever a **user** tries to delete its own created thread by pressing a "Delete" button, this error appears in console:

**Uncaught Attempted to open modal 'delete-thread' but no such modal found.**

However, after pressing CTRL+F5 (refreshing the page) or waiting a few seconds after the thread page loads , this issue disappears

**Comment by Riari** [comment]
I was able to replicate this on the demo - will take a look ASAP. Thanks for reporting!

**Comment by Riari** [comment]
Should be fixed by #282, which also addresses a bunch of other stuff I noticed. I'll create a new release imminently and get the demo updated.
