### ISSUE TITLE
Missing required parameter for [Route: forum.post.create] [URI: forum/t/{thread}-{thread_slug}/reply] [Missing parameter: thread_slug].

### ISSUE THREAD

**Issue by w3yyb** [Riari/laravel-forum#283]
when the thread title is chinese then the homepage

display:

Missing required parameter for [Route: forum.post.create] [URI: forum/t/{thread}-{thread_slug}/reply] [Missing parameter: thread_slug].

**Comment by Riari** [comment]
Titles get "slugified" on the fly via the `Forum::slugify($title);` utility method, which only wraps Laravel's `str_slug()` by default, but you can override it to generate the slugs in your preferred way. See https://www.teamteatime.net/docs/laravel-forum/5/web/helpers/ for more details.
