### ISSUE TITLE
Deleting selected thread gives a 500 Error

### ISSUE THREAD

**Issue by dBaliukynas** [Riari/laravel-forum#286]
Reproducing this bug:

Go to a category, select a thread that you want to delete. Select delete permanently, and eventually get an error.

However, when deleting a thread from inside the thread itself, this error does not occur

Illustration: 
https://imgur.com/a/AXlCfYi

**Comment by Riari** [comment]
Fixed in release [5.2.1](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.2.1). Thanks for reporting!
