### ISSUE TITLE
Permanently deleting soft-deleted thread throws uncaught error

### ISSUE THREAD

**Issue by dBaliukynas** [Riari/laravel-forum#289]
Reproducing this bug:

1. Go to thread.
2. Soft-delete thread (press Delete but do not select permanently delete)
3. Go back to soft-deleted thread
4. Press permanently delete
5. Get an uncaught error in console

Illustration: https://imgur.com/a/aE1XjCf

Tested in Team Tea Time's Laravel Forum Demo (https://laravel-forum.teamteatime.net/)

**Comment by Riari** [comment]
Fixed in #295.
