### ISSUE TITLE
Uncaught Attempted to open modal 'undefined' but no such modal found when clicking on a button icon

### ISSUE THREAD

**Issue by dBaliukynas** [Riari/laravel-forum#290]
Clicking on a button icon will throw an uncaught error. As far as I tested, it happens with all the buttons that have icons.

Reproducing this bug:

1. Create thread
2. Click on any icon inside a button
3. Get an error

Video Illustration: https://youtu.be/KiAf4EFtCeM

Tested in Team Tea Time's Laravel Forum Demo (https://laravel-forum.teamteatime.net/)

**Comment by Riari** [comment]
Fixed in #295.
