### ISSUE TITLE
Uncaught Attempted to open modal 'delete-category' but no such modal found.

### ISSUE THREAD

**Issue by dBaliukynas** [Riari/laravel-forum#291]
When trying to delete a category, an uncaught error is being thrown.

Reproducing this bug:

1. Manage categories
2. Press delete
3. Get an uncaught error

It seems like the categories that doesn't have threads or have other sub categories are producing this bug. However, a category with threads seems to open the modal without errors, as seen in the video.

Video Illustration: https://youtu.be/fWugbmW0iVw

Tested in Team Tea Time's Laravel Forum Demo (https://laravel-forum.teamteatime.net/)

**Comment by Riari** [comment]
Fixed in #295.
