### ISSUE TITLE
Uncaught Attempted to open modal 'undefined' but no such modal found when clicking on a button icon

### ISSUE THREAD

**Issue by dBaliukynas** [Riari/laravel-forum#299]
Clicking on a button icon will throw an uncaught error. As far as I tested, it happens with all the buttons that have icons.

Reproducing this bug:

Click on any icon inside a button
Get an error
Video Illustration: https://youtu.be/KiAf4EFtCeM

Tested in Team Tea Time's Laravel Forum Demo (https://laravel-forum.teamteatime.net/)

**Apparently, this issue is still present in current demo.**

**Comment by Riari** [comment]
This was fixed in a previous release, I just hadn't carried the fix over to the demo's version of the master view. Thanks for reporting!
