### ISSUE TITLE
Showing SoftDeleted Posts with Normal Posts

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#30]
How would I go about doing that?
I can't seem to get that done in the view.

**Comment by Riari** [comment]
You'd need to override the `Threads` repository, and specifically the `getByID()` method, so that it returns the thread with soft deleted posts included (see http://laravel.com/docs/5.1/eloquent#querying-soft-deleted-models).

Not sure why you'd want to do this though, at least without a 'view post' permission (which doesn't exist currently).

**Comment by Denoder** [comment]
well im trying to mix it with the boilerplate access methods, so if "this" user can "delete posts" then the SoftDeleted Posts Will show, which then allows for Perma Deletions.

**Comment by Denoder** [comment]
it's confusing for me if im not given examples <_<

**Comment by Riari** [comment]
Ah, I see what you mean. That would be workable then, though my original suggestion probably isn't the best way of doing it. Instead, you could try adding an attribute to the Thread model that fetches all of the thread's posts. I'm not sure how exactly, but when I get a chance to investigate I'll see if I can give an example.

Edit: and then you can simply use the `$post->canDelete` in the post view to conditionally show elements as needed.

**Comment by Denoder** [comment]
okay, for now ill just disable soft deletes.

**Comment by Riari** [comment]
Okay, try this: in `Models/Thread.php`, change

```
    public function getPostsPaginatedAttribute()
    {
        return $this->posts()->paginate(config('forum.preferences.posts_per_thread'));
    }
```

to

```
    public function getPostsPaginatedAttribute()
    {
        return $this->posts()->withTrashed()->paginate(config('forum.preferences.posts_per_thread'));
    }
```

(Add `->withTrashed()` to the method chain, basically)

That's all you should need to do to make soft deleted posts show up in threads. Then, I'd wrap each post (either in `thread.blade.php` or `partials/post.blade.php`) in a `@if(!$post->trashed() || ($post->trashed() && $post->canDelete))` so they only show up for users who have the delete perm.

**Comment by Denoder** [comment]
yea that works.

**Comment by Riari** [comment]
Cool. I'll keep this in mind as an optional feature in v3.

**Comment by Denoder** [comment]
Decided to wait until v2.0.0 is finished since i have other things on my plate regarding Laravel.
