### ISSUE TITLE
Can't get the permission working

### ISSUE THREAD

**Issue by Edan0615** [Riari/laravel-forum#303]
Hello, thanks for the amazing work!

I've finally managed to get it working, but there's one problem that I can't seem to solve after reading documents and articles online, which is to use policy to permit certain action.

What I wanna do is just like the demo, different user has their own permission, however no matter how I configure the code it's always allowed any users to do something only the admin should be able to do.

I have been searching for the policy code, but can't find it, I was wondering if you could help~

**Comment by Edan0615** [comment]
Hey I know this might be stupid, but I actually did looking for the file and failed, which results in that I couldn't rewrite the policy as I wish, and I asked.

However, I just did find out it's inside the vender folder and inside a folder name called "riari", and I figure someone may need this. so I would like to left it here in case it would be helpful for someone

**Comment by Riari** [comment]
Hi,

Glad you were able to find the policies. Just to be clear though, you shouldn't modify anything inside the vendor directory. In this case, what you should do is create a class somewhere in your application that extends the policy you want to modify, then override the specific methods you want to change.

Once you've done that, you can update the `forum.integration.policies` config value to tell the package to use your class instead of the one that ships with the package.

This is documented at https://www.teamteatime.net/docs/laravel-forum/5/policies/ but it's not very clear. I may introduce a command to help make this process easier.

I hope that helps!

**Comment by Edan0615** [comment]
Oh yeah!! Thank you! As matter of fact, I just finished configured the file inside the vender folder as I wished, and ready to deploy it on to my server.

Thank you I will work on that now, btw I am thinking about adding the traditional Chinese if you don't mind since the one we have is the simplified one.

Once again, I can't be more thankful for you work.If it's okay I am thinking about recording a couple of videos teaching people how to use this lovely project in Chinese.

**Comment by Riari** [comment]
You're welcome! Any contributions are received with gratitude :)

**Comment by Edan0615** [comment]
Sorry to keep asking just one question, I created files in my app folder (pretty much copied what I configured the one in the vender folder) and I change the polices route from the orignal to app\Policies\xyz::class, and it says it couldn't find it. 

I was wondering if I did anthing wrong cause I am quite positive that it is there.

**Comment by Riari** [comment]
Did you update the file's namespace accordingly? The autoloader generated by Composer should be able to find new class files as long as they're placed somewhere in your `app/` directory and have an appropriate namespace.

You could try running `composer dump-autoload` but that shouldn't be necessary.

**Comment by Edan0615** [comment]
Hello sir, thanks for the response. 

After receiving this, I went to where the new files are and change the thing after the key word "namespace" to App\xyz; and then it gives me 
`Class "TeamTeaTime\Forum\Policies\ForumPolicy" not found`

I am quite new to use others' laravel work, so it might be stupid, sorry~~

I haven't run the composer dump-autoload since I find it may not be this, judging by the error message.

**Comment by Edan0615** [comment]
OHOHOHOHOHO!!!! I changed the one in the vender folder, like mixed them in my vscode so I couldn't find it correct.

After configuring it correctly, like you suggested, and it worked. 

Sorry, you know I have been working on this package from 8am till now so my brian kinda stuck.
Thank you, I have finally got it working, and I beleive my future users who use this would also be greatly appreciated.

**Comment by Riari** [comment]
Excellent! Glad you were able to figure it out.

For future reference, I'm going to give a full example of how this process should look. You probably don't need this, but it may be useful to others who stumble across this issue.

Let's say you want to override the `CategoryPolicy::createThreads` action. In that case, you would:

1) Create `app/Policies/Forum/CategoryPolicy.php`:

```php
<?php

namespace App\Policies\Forum;

use TeamTeaTime\Forum\Policies\CategoryPolicy as ForumCategoryPolicy;
use TeamTeaTime\Forum\Models\Category;

class CategoryPolicy extends ForumCategoryPolicy
{
    public function createThreads($user, Category $category): bool
    {
        // your logic here
    }
}
```

2) Update `forum.integration.policies`. Assuming you don't override any of the other policies, it should look like this:

```php
    'policies' => [
        'forum' => TeamTeaTime\Forum\Policies\ForumPolicy::class,
        'model' => [
            TeamTeaTime\Forum\Models\Category::class => App\Policies\Forum\CategoryPolicy::class,
            TeamTeaTime\Forum\Models\Thread::class => TeamTeaTime\Forum\Policies\ThreadPolicy::class,
            TeamTeaTime\Forum\Models\Post::class => TeamTeaTime\Forum\Policies\PostPolicy::class,
        ],
    ],
```

And that's it. It's only two steps, but how the class extension should look may not be obvious to everyone. I'll probably put this example in the docs as well.

**Comment by Edan0615** [comment]
Yeah no problem, and that's exactly what I did. 

BTW, I don't know if it's just me or someone might also run into the same place like me when I first tring to use this lovely project which is finding the 'forum.integration.policies' to be an actual file name, however in fact, the last one it's actually an array value, or to be precise, key.

Just figure someone may need this.
