### ISSUE TITLE
Missing required parameter for [Route: forum.thread.show]

### ISSUE THREAD

**Issue by Edan0615** [Riari/laravel-forum#304]
`Missing required parameter for [Route: forum.thread.show] [URI: forum/t/{thread}-{thread_slug}] [Missing parameter: thread_slug].`

Hello, it's me again it's kinda werid that it works fine on my localhost, but when I uploaded it onto my server and when I tried to test it, I accidently leave content as blank, and it gave me the above message.

and when I am typing this here, I figure I might as well just delete the post from the DB, and when I went in there I found five or six same posts, and when delete them it's back and works fine.

I was wondering if this could cause any problem since user tend to make this kind of mistake.

**Comment by Riari** [comment]
What language did you write the thread titles in? This issue may be relevant: #283

**Comment by Edan0615** [comment]
> What language did you write the thread titles in? This issue may be relevant: #283

It's Chinese~~ 
so could you tell me where should add the code mentioned in the doc? so that I won't stumble anything again!

**Comment by Riari** [comment]
See https://www.teamteatime.net/docs/laravel-forum/5/web/helpers/. In short: you need to extend `TeamTeaTime\Forum\Support\Web\Forum` with a new class, point `forum.web.utility_class` to that class, then override the `slugify` method with an implementation that works with unicode (or at least with Chinese characters).

It's up to you to decide on the implementation, but you could for example use https://github.com/ausi/slug-generator in that method.

**Comment by Edan0615** [comment]
Oh yeah if you don't mind that since I delete 5 threads and add 1 so it should be 1 thread, but it still says 6. is it because that it uses cache or is it because it uses the some method that didn't count the real posts?

> `Missing required parameter for [Route: forum.thread.show] [URI: forum/t/{thread}-{thread_slug}] [Missing parameter: thread_slug].`
> 
> Hello, it's me again it's kinda werid that it works fine on my localhost, but when I uploaded it onto my server and when I tried to test it, I accidently leave content as blank, and it gave me the above message.
> 
> and when I am typing this here, I figure I might as well just delete the post from the DB, and when I went in there I found five or six same posts, and when delete them it's back and works fine.
> 
> I was wondering if this could cause any problem since user tend to make this kind of mistake.

**Comment by Riari** [comment]
Thread and post statistics are written to DB rows. More specifically, the thread and post counts for a category are written to that category's row and get updated when you create or delete threads/posts via the frontend or API. So if you manually drop rows in the DB, they won't get updated.

You can run `php artisan forum:sync` to force a re-sync of those numbers.

**Comment by Edan0615** [comment]
> See https://www.teamteatime.net/docs/laravel-forum/5/web/helpers/. In short: you need to extend `TeamTeaTime\Forum\Support\Web\Forum` with a new class, point `forum.web.utility_class` to that class, then override the `slugify` method with an implementation that works with unicode (or at least with Chinese characters).
> 
> It's up to you to decide on the implementation, but you could for example use https://github.com/ausi/slug-generator in that method.

Yeah I think I just got an 500 server error again, let me try and use this solution

**Comment by Edan0615** [comment]
Oh yeah, `  Package ausi/slug-generator has requirements incompatible with your PHP version, PHP extensions and Composer version:  ` 

Well, guess it's a sign for another long debug hours?

**Comment by Edan0615** [comment]
Hello, so I was wondering if you have another option, I have been working around the one you suggested but doesn't seem to get it working. 

I tried to just encoded it as unicode or utf8, however it's not working~

**Comment by Riari** [comment]
Sorry I didn't reply to this sooner. I don't think I can be of much help because I've never worked with that package before - although I don't see why it shouldn't work. Seems like you have some missing PHP extensions, an old PHP version, or some other dependency version issue preventing it from working.

Ultimately, the implementation is up to you because it's not a very simple problem so solve and the solution varies depending on the target audience of the forum and how exactly you want the URLs to look. That's why the provided `Slugify` method is so basic, and it's why Laravel's own `Slug` string helper is also basic.

I'm going to close this issue now, but feel free to reply again if you have any more specific questions.
