### ISSUE TITLE
Sanitation of input

### ISSUE THREAD

**Issue by ghost** [Riari/laravel-forum#310]
What is being used to sanitize the input? I am using Purify site wide. Was thinking of incorporating this. What can you tell me about the sanitization of the input?

**Comment by Riari** [comment]
There are three aspects to making user input secure in this package:

* Input validation. Fields are validated as strings, numeric, etc as appropriate using Laravel's built-in validator.
* Prepared statements. Insert queries (at least the ones involving string fields) are done via Eloquent and benefit from built-in protections.
* Output encoding. By default, category titles, category descriptions, and thread titles are output using the `{{ }}` Blade syntax, which passes the content through [e](https://laravel.com/docs/9.x/helpers#method-e). Post content goes through the `Forum::render` utility method, which goes through the same encoding function but preserves line breaks with `nl2br`.

I don't know what Purify is, but there's no need to use it here. If you want to allow a subset of HTML in user posts then it may be useful for that (in which case you'll need to override the `Forum::render` method by extending `TeamTeaTime\Forum\Support\Web\Forum` and overriding the `forum.web.utility_class` config value).

**Comment by ghost** [comment]
thank you Sir... will look into the markup saving.
