### ISSUE TITLE
How I can count the number of posts by user

### ISSUE THREAD

**Issue by lucasprevidelli** [Riari/laravel-forum#329]
Hello, How I can count the number of posts by user?

**Comment by Riari** [comment]
Hi,

For this, you can add the [`TeamTeaTime\Forum\Models\Traits\HasForumContent` trait](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/src/Models/Traits/HasForumContent.php) to your User model - this will enable you to get a thread count with `$user->threads()->count()` or a post count with `$user->posts()->count()`.

**Comment by lucasprevidelli** [comment]
![image](https://user-images.githubusercontent.com/15057158/199104296-21620160-6199-4907-9493-7c1a97a6b08d.png)

![image](https://user-images.githubusercontent.com/15057158/199104420-c26d3998-8e7f-4f70-89e3-7853e2279110.png)
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/15057158/199104450-7d7aab25-5e27-4806-a23b-e90402171dd0.png">

is right?

**Comment by Riari** [comment]
You need to use `$post->author` there instead.

`$post->author->threads()->count()` and `$post->author->posts()->count()`.
