### ISSUE TITLE
Allow indefinite nesting

### ISSUE THREAD

**Issue by Riari** [Riari/laravel-forum#33]
Currently, top-level categories can only have one level of children. This should be changed to allow indefinite nesting and should have sensible default views to handle 3 or more levels.

**Comment by Denoder** [comment]
oh for the auth class, you can use:

```
auth()->check()
and
auth()->user()
```

without having to call the Auth namespace, this also applies to the View Namespace and the App Namespace and the Config Namespace. (Just a little tip)

**Comment by Riari** [comment]
Ah, good to know. I knew about `config()` and `view()` but not the others. I'll update all the facade calls to use those instead. Thanks.

**Comment by Denoder** [comment]
yea they did it to simplify the use of adding authentication. and to reduce the infinite lines of "use Auth; (etc)" >_>

**Comment by Riari** [comment]
The `use` statements weren't necessary for facades in Laravel 4 because controllers (and several other classes) weren't namespaced by default in L4. So I imagine it had a lot to do with that, to provide alternative access to the facades once everything became namespaced.

**Comment by Denoder** [comment]
and here's the entire arsenal of helper functions for laravel's core:
http://pastebin.com/NAbHtyfN

**Comment by Denoder** [comment]
Oh and to your previous question asked in some other post, yes I am using this in production <_<
There's no fun in it if something doesn't break for me. My members know I do this.... A Lot.

**Comment by Riari** [comment]
That's... a really bad idea, but hey, as long as your users aren't paying for anything, knock yourself out I guess.

**Comment by Riari** [comment]
Also, locking this for now since none of the comments so far have anything to do with this issue, lol.

**Comment by Riari** [comment]
Addressed in 02a9367.
