### ISSUE TITLE
How to show recent threads

### ISSUE THREAD

**Issue by nolsen89** [Riari/laravel-forum#332]
Sorry for my newbie question, but i have search around and can not find an example on how to call an event in the homecontroller.

i wont to call UserViewingRecent in my HomeController and show them on my homepage.
i am new with package and can not find an example or explanation on how to call and use events.

is it possible to show an example on how to for us noobs?

**Comment by Riari** [comment]
Hi,

Events are not supposed to be called by you; they're raised by the package when certain actions are done by the user. You can [define listeners](https://laravel.com/docs/9.x/events#defining-listeners) to react to specific events. An example of what you'd use most of these events for is to build a list of users and their current activities.

If you just want to display a list of recent threads on your homepage, you can use the `TeamTeaTime\Forum\Models\Thread` model directly. See the [ThreadController::recent method](https://github.com/Team-Tea-Time/laravel-forum/blob/5.0/src/Http/Controllers/Web/ThreadController.php#L32-L42) for an example of how you might use it (note the filtering to prevent users from seeing threads in categories they cannot access).

In the future, this kind of logic might be moved to service classes with some options to control the output (e.g. pagination limit). I hope this helps in the meantime!

**Comment by nolsen89** [comment]
so this is my controller:
  namespace App\Http\Controllers;
  use TeamTeaTime\Forum\Models\Thread;
  class HomeController extends Controller
  {
      public function index()
      {
          $threads = Thread::recent()->with('category', 'author', 'lastPost', 'lastPost.author', 'lastPost.thread');
  
          return view('index', [
              'metaTitle' => 'Home',
              'metaDescription' => 'Description',
              'title' => 'Home',
              'threads' => $threads,
          ]);
      }
  }

And here is my index view:
  <div id="new-posts">
                  @if ($threads)
                      <div class="threads list-group my-3 shadow-sm">
                          @foreach ($threads as $thread)
                              @include ('forum::thread.partials.list')
                          @endforeach
                      </div>
                  @else
                      <div class="card my-3">
                          <div class="card-body text-center text-muted">
                              {{ trans('forum::threads.none_found') }}
                        </div>
                    </div>
                @endif
            </div>
But i do not get any results?? can you see what i am doing wrong?

and when i var_dump $threads i get this message
Allowed memory size of 792723456 bytes exhausted (tried to allocate 400572416 bytes)

**Comment by Riari** [comment]
You need to execute the query builder to get the threads:
```
$threads = Thread::recent()->with('category', 'author', 'lastPost', 'lastPost.author', 'lastPost.thread')->get();
```
Also, don't forget to do the filtering I mentioned. If you don't, `$threads` may include threads that the user doesn't have permission to view. If all of your categories are publicly visible, then this doesn't matter as much, but you should probably still implement it in case category permissions ever change.

**Comment by nolsen89** [comment]
Thank you so much, it works now..
