### ISSUE TITLE
Feature Request: Show quote message while replying?

### ISSUE THREAD

**Issue by niels-numbers** [Riari/laravel-forum#333]
At the moment, if you click reply, you do not see the original message anymore:

![image](https://user-images.githubusercontent.com/1765602/201561672-40458371-5a20-4518-8238-78f12cdb809a.png)

![image](https://user-images.githubusercontent.com/1765602/201561798-318a8c05-2826-4827-ab7d-73d8741f3de2.png)

I think it makes sense to see the reply and user here, so one can first validate that you are actually replying to the correct one, and if the user made a very long answer, you can structure your reply accordingly and don't need to keep original one in your mind.

Is that something you are planning to do or would you be willing to consider a PR?

**Comment by Riari** [comment]
Hi,

Looks like this was broken by a recent change - it's not intentional. A PR would be great if you have some time to investigate and fix it - otherwise I can take a look later in the week.

Thanks!

**Comment by Riari** [comment]
Fix released in [5.4.1](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.4.1).
