### ISSUE TITLE
Problem when I deploy the application

### ISSUE THREAD

**Issue by lucasprevidelli** [Riari/laravel-forum#335]
Hi, after upload the application in Hostinger, the translate doesn't work

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/15057158/203105811-bd5f57c7-166b-4156-aa98-cbf3397f9d97.png">

**Comment by Riari** [comment]
Hi,

I have some questions to help narrow down the issue:

1. Did you run `php artisan vendor:publish` to publish the package files? (I assume you did as I don't think it would work at all otherwise, but want to check)
2. What is your app locale set to?
3. What is your app `fallback_locale` set to?

**Comment by lucasprevidelli** [comment]
Hi, I run now after upload for ssh. The host is sharing. the locale is pt-br

![image](https://user-images.githubusercontent.com/15057158/203109366-ed50fb83-6f5c-46a1-984b-349bfe5decf0.png)

**Comment by lucasprevidelli** [comment]
![image](https://user-images.githubusercontent.com/15057158/203111217-30922207-c497-4641-9854-3522971708e1.png)

**Comment by Riari** [comment]
That's weird. It should work, although the locale name in this package is `pt-br` and it may be case sensitive. What happens if you change your fallback locale value to `'pt-br'`?

**Comment by lucasprevidelli** [comment]
OMG! Works. Thanks

**Comment by Riari** [comment]
Excellent! Glad I could help :)
