### ISSUE TITLE
Not issue. Just guide me how to setup permission? Please!

### ISSUE THREAD

**Issue by truongxxxx** [Riari/laravel-forum#336]
Please tell me how to setup forum permission. 
I had install forum, but everyone can add category ... like a mod.
Thank so much

**Comment by Riari** [comment]
Hi,

You just need to extend the package's policy classes, override the methods you want to change, and change the class namespaces in the config to point to your policies. This is outlined in the docs here: https://www.teamteatime.net/docs/laravel-forum/5/policies/

You can also find a more detailed example about hooking policies up to a permission/role system here: https://github.com/Team-Tea-Time/laravel-forum/issues/323#issuecomment-1286830874

**Comment by truongxxxx** [comment]
Thanks Riari. I will try following your instructions
