### ISSUE TITLE
Problem with having translation files in resources/lang 

### ISSUE THREAD

**Issue by ianfagg** [Riari/laravel-forum#342]
Hi, I've installed laravel-forum successfully but my application uses the /lang directory in the route rather than /resources/lang where your package copies the files. After installing it has broken my site. If I remove /resources/lang directory my site works OK but obviously it breaks the forum (I've moved the /vendor/forum directory into my /lang directory). Do you know how I might be able to fix this i.e. change where laravel-forum looks for the translations? Any help will be much appreciated. Thanks, Ian

**Comment by Riari** [comment]
Hi,

How did your change your app's lang path? I can't find anything in the Laravel docs about doing that, so it seems like an unconventional change, but I may be completely mistaken. I'm hesitant to make any changes to the package that would support this case unless it's also officially supported by the framework.

Let me know and we can go from there! I might be able to help come up with a workaround at least.

**Comment by ianfagg** [comment]
Hi, Thanks for the quick reply.I’ve not changed anything, it’s the default now in Laravel, it was added there when I installed Laravel. So it could be an issue for others in the future I think.Hopefully we can find a way to overcome this.Loving your forum package by the way, it’s just what I need, looks really easy to customise. I’ll keep playing around and will let you know if I find a solution but I’m no expert. Cheers, IanOn 27 Jan 2023, at 18:44, Rick Mann ***@***.***> wrote:﻿
Hi,
How did your change your app's lang path? I can't find anything in the Laravel docs about doing that, so it seems like an unconventional change, but I may be completely mistaken. I'm hesitant to make any changes to the package that would support this case unless it's also officially supported by the framework.
Let me know and we can go from there! I might be able to help come up with a workaround at least.

**Comment by Riari** [comment]
Ah I see! Clearly I've not been keeping up with Laravel updates as well as I should be!

In that case, I think I'll add a config option to specify the path. I'll get back to you on this.

**Comment by ianfagg** [comment]
Yes, that sounds great! Thanks very much. All the best, IanOn 27 Jan 2023, at 19:54, Rick Mann ***@***.***> wrote:﻿
Ah I see! Clearly I've not been keeping up with Laravel updates as well as I should be!
In that case, I think I'll add a config option to specify the path. I'll get back to you on this.

**Comment by Riari** [comment]
I decided instead to update the service provider to check for the existence of the [`lang_path`](https://laravel.com/docs/9.x/helpers#method-lang-path) helper, since that was introduced with Laravel 9 alongside the path change. I think it's the simplest solution - it maintains backwards compatibility and doesn't require users to modify a config value.

Anyway, see if the new release (5.4.3) works for you. In the unlikely event that it doesn't, let me know and I'll see what I can do!

**Comment by ianfagg** [comment]
Hi Rick,

Great stuff.

I deleted my existing /lang/vendor folder and the /views/vendor/forum folders, did a composer remove then require the package, so I can see it’s now 5.4.3. Followed by artisan vendor:publish.

So it’s now installing the files in my /lang/vendor folder.

But the front end is still not displaying the translations unfortunately. Is there something else I need to do?

All the best, Ian

**Comment by Riari** [comment]
Hey, sorry for the late reply. I'll try to investigate this soon.

**Comment by ianfagg** [comment]
Hi Rick,

I’ve had a bit of joy with this. I think the problem is my app uses ‘en_GB' instead of ‘en’ for the translation files. If I rename the directories in /lang/vendor/forum appropriately it all works fine.

So maybe we also need to determine which locale structure is being used if that’s possible? Happy to just rename my folders for the moment so no rush in finding a solution. But I thought it might help you.

Thanks so much for your help with this, really appreciate it.

Ian

**Comment by Riari** [comment]
Glad you were able to figure it out. It's an interesting detail that I'll look into at some point.

Sadly there has been a somewhat unexpected death in my family, so I won't be working on the package for a little while.

I'll keep this issue open so I won't forget to come back to it. Thanks for reporting it.

**Comment by ianfagg** [comment]
Really sorry to hear that, my condolences.

All the best, Ian

**Comment by Riari** [comment]
Just following up on this - I've taken a look and I see two options to improve this. One option is that I add a config option with an associative array mapping package locales to app locales, so for example `en` could be mapped to `en_GB` with `'en' => 'en_GB'`.

The other option is for the app to specify `en` as its `app.fallback_locale` value, which requires no changes to the package but might not be suitable depending on the app's exact locale arrangement.

I suppose a third option would be to create a symlink from the directory the package is trying to find (`en`) to the one present in the app (`en_GB`).

I think I'll close this issue for now as I'm not entirely sure about the first option, but happy to re-open it if any further discussion comes up.
