### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_CLOSED all.min.css:1     Failed to load resource: net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by RaoKamranshauket** [Riari/laravel-forum#348]
I am using laravel 8.1 version unable to find this error
Failed to load resource: net::ERR_CONNECTION_CLOSED
all.min.css:1     Failed to load resource: net::ERR_CONNECTION_CLOSED
One more thing:
I'm also not track where $activeTemplateTrue is initialized, Your help highly appreciate   
href="{{asset($activeTemplateTrue.'frontend/css/lib/bootstrap.min.css')}}

**Comment by Riari** [comment]
Hi,

Unfortunately those errors are unrelated to this package - there is no `all.min.css` or `$activeTemplateTrue`. The errors must be coming from somewhere in your app or a different package.

Closing this, but good luck in finding solutions!
