### ISSUE TITLE
Routes category

### ISSUE THREAD

**Issue by Bbeeff2510** [Riari/laravel-forum#351]
Hey Riari!
I have integrated the forum into my application, but I have a problem. I already have product categories and a category model.
after I installed the forum - my categories stopped working, when I try to access them - I get a 404 error because my application is trying to look up categories in the forum_categories table.
I thought it had something to do with routes and it turned out to be so.

In the wep.php forum file, I remove the snippet:
$r->bind('category', function ($value) {
    return \TeamTeaTime\Forum\Models\Category::findOrFail($value);
});

And after that, my categories start working, but at the same time, forum categories stop being deleted / edited.

Can you please tell me how to solve this problem?

**Comment by Riari** [comment]
Hi,

Which package version are you using? Route model bindings were removed as of [5.3.5](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.3.5), so this issue shouldn't occur as long as you use that or a newer version.

**Comment by Bbeeff2510** [comment]
> Привет,
> 
> Какую версию пакета вы используете? Привязки модели маршрута были удалены с [версии 5.3.5](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.3.5) , поэтому эта проблема не должна возникать, пока вы используете эту или более новую версию.

У меня приложение на laravel 6. Я использую версию 5.0

Мне нужно обновлять laravel?

**Comment by Bbeeff2510** [comment]
> Привет,
> 
> Какую версию пакета вы используете? Привязки модели маршрута были удалены с [версии 5.3.5](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.3.5) , поэтому эта проблема не возникла, пока не возникла эта или более новая версия.

My app is in laravel 6. I am using version 5. do i need to update laravel?

**Comment by Riari** [comment]
I would urge you to upgrade Laravel, yes. Going from 6 to 10 shouldn't be too difficult if you just follow the upgrade guides in the Laravel docs.

Otherwise, I think your only option would be to use a parameter name other than 'category' in your application.

**Comment by Bbeeff2510** [comment]
> Я бы призвал вас обновить Laravel, да. Переход с 6 на 10 не должен быть слишком сложным, если вы просто будете следовать руководствам по обновлению в документации Laravel.
> 
> В противном случае, я думаю, единственным вариантом будет использование в приложении имени параметра, отличного от «категории».

Thank you! I think this issue can be closed! We will update...
