### ISSUE TITLE
UserRestoredPost and UserDeletedPost does not fire

### ISSUE THREAD

**Issue by ghost** [Riari/laravel-forum#352]
Upon adding a set of listeners, I noticed that the `TeamTeaTime\Forum\Events\UserDeletedPost` and `TeamTeaTime\Forum\Events\UserRestoredPost` never fires.

In the respective file (eg. https://github.com/Team-Tea-Time/laravel-forum/blob/5.6.0/src/Http/Requests/RestorePost.php) the issue is caused by the following line 29:

` if (! $post === null) {`

It should be corrected:

` if ($post !== null) {`

Great package!

**Comment by Riari** [comment]
Thanks for reporting this!
