### ISSUE TITLE
Installation on a multi-site points to the wrong db for posts

### ISSUE THREAD

**Issue by seatechdev** [Riari/laravel-forum#354]
Hi I am using a multi-site installation where a COMMON_DB_DATABASE is used to provide authentication/session across multiple laravel installations.  Then I have a DB_DATABASE which local to the laravel app where laravel-forum is installed.  After running the migration, all laravel-forum tables were installed in the DB_DATABASE.    However, I can create new categories.  However, when I create a new post under a cateogry or try to view it, it points me to the COMMON_DB_DATABASE.    I get the following error

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'commondb.forum_threads_read' doesn't exist (SQL: select `users`.*, `forum_threads_read`.`thread_id` as `pivot_thread_id`, `forum_threads_read`.`user_id` as `pivot_user_id`, `forum_threads_read`.`created_at` as `pivot_created_at`, `forum_threads_read`.`updated_at` as `pivot_updated_at` from `users` inner join `forum_threads_read` on `users`.`id` = `forum_threads_read`.`user_id` where `forum_threads_read`.`thread_id` = 1 and `forum_threads_read`.`user_id` = 1 limit 1)

```

**Comment by Riari** [comment]
Hi,

I'm not sure how exactly this is happening since the package doesn't specify which database connection to use (either in its models or when using them) - whatever is causing it to use one connection for the migrations and a different one for data must be caused by something in your application.

Unfortunately the package isn't really designed to handle this scenario anyway, but it wouldn't take much work to allow connections to be specified for each model in the config. I can take a look at doing this when I next have time to work on it, or you can open a PR if you think this would solve your problem.

**Comment by seatechdev** [comment]
Thanks! Do you know which file in the package it gets $this->user() from?  I went through your code but I couldn't pin point it.  I can get the user details from my user table in the other db and apply to $this->user().

**Comment by Riari** [comment]
Any occurrences of `$this->user()` you see are almost certainly in the request classes, which all inherit `Illuminate\Foundation\Http\FormRequest`. The package doesn't implement its own method for obtaining the authenticated user, it just accesses the user provided by Laravel.

**Comment by seatechdev** [comment]
Thanks.  So all my commondb does is provides authentication.  I am using it for other sites too.  The main db is still local to the installation.  Not sure why it then looks at the commondb.

**Comment by seatechdev** [comment]
The files it fails at  
 - resources/views/vendor/forum/thread/partials/list.blade.php line:22
 - resources/views/vendor/forum/category/show.blade.php line:62

I also checked that it looks up the user accurately from my commondb.  Just not sure why it looks for the remainder of the tables there.

**Comment by Riari** [comment]
I've looked into this further and I think the issue definitely stems from the fact the package models don't specify a connection. I think what is happening is when the package tries to access a user relationship on a model (such as `Thread::readers()`), Laravel uses the connection used for the user model for the whole query rather than splitting it up.

Introducing config options to specify model connections should fix this. Could you do me a favour and test this by modifying the Thread and Post model files in the package directory? Add a `protected $connection = 'connection_name';` to them both, then see if it all works correctly. If it does, I'll work on a PR to add the options.

**Comment by seatechdev** [comment]
I have tried connections as ``` protected $connection = 'mysql'; ``` which is the db where forum content is supposed to sit.  But it doesn't work.    The reason the threads query fails is because it is tries an inner join with the user table that is on a different database.  

``` SQL: select `users`.*, `forum_threads_read`.`thread_id` as `pivot_thread_id`, `forum_threads_read`.`user_id` as `pivot_user_id`, `forum_threads_read`.`created_at` as `pivot_created_at`, `forum_threads_read`.`updated_at` as `pivot_updated_at` from `users` inner join `forum_threads_read` on `users`.`id` = `forum_threads_read`.`user_id` where `forum_threads_read`.`thread_id` = 1 and `forum_threads_read`.`user_id` = 66 limit 1 ```

**Comment by Riari** [comment]
> The reason the threads query fails is because it is tries an inner join with the user table that is on a different database.

I know - Eloquent is supposed to handle this case as long as connections are explicitly set on each model as far as I can tell. Do all of your application models have connections set on them?

**Comment by seatechdev** [comment]
Thanks for the follow up.  Yes, On this instance of Laravel, I have connections specifically set for laravel-forum (files under laravel-forum/src/Models and laravel-forum/src/Models/Traits) and user model (App/Models/User).  Is there a way to skip the joins mentioned above?  I could care less if user see whether they have read the thread or not not.  On the home page of forum it renders categories and links to latest posts.

**Comment by elbojoloco** [comment]
@seatechdev Could you share more about the setup of your `User` model and logic regarding your default `DB_DATABASE` and switching to use `COMMON_DB_DATABASE`? When do you decide which database to use, and where do you decide this? Most likely at some point during the described flows in your initial post, you've switched to a different database on a global level, forcing the package to use that database as well instead of your regular `DB_DATABASE`.

**Comment by seatechdev** [comment]
@elbojoloco  - In the .env file I have the following: 
```
DB_CONNECTION=mysql
DB_HOST=database-host-path
DB_PORT=3306
DB_DATABASE=forum
DB_USERNAME=username
DB_PASSWORD=password


COMMON_DB_CONNECTION=mysql
COMMON_DB_HOST=database-host-path
COMMON_DB_PORT=3306
COMMON_DB_DATABASE=userdb
COMMON_DB_USERNAME=username
COMMON_DB_PASSWORD=password
```

In my config/database.php file

```
 'default' => env('DB_CONNECTION', 'mysql'),

  'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            .... All other information just saving some space
],

'common_database' => [
            'driver' => 'mysql',
            'url' => env('COMMON_DATABASE_URL'),
            .... All other information just saving some space
],

```

Then in my App/Models/User.php

```
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
        protected $connection = 'common_database';

````

Then all files under files under laravel-forum/src/Models and laravel-forum/src/Models/Traits I use the following pattern for each class and trait. I'm using the Category.php as an example.

```
class Category extends BaseModel
{
    use NodeTrait;
protected $connection = 'mysql';


```

The root cause seem to be an inner join over two different databases.

**Comment by Riari** [comment]
I think I'll need to take some time to try and reproduce your setup and experiment with it. I'll get back to you when I have more info.

**Comment by Riari** [comment]
OK, I've spent some time on this and I think a working solution for your case is to specify the database name in the table property for each model. Could you try this and verify that it works on your side?

1. Update your user model `$table` property to specify the common DB: `protected $table = 'commondb.users';`
2. Update the Category, Thread, and Post models to prefix their table names with the other DB
3. In the Thread model, prefix the value of the `READERS_TABLE` const as well

This should force Eloquent to select from the correct databases regardless of whether a connection is specified on the models. Obviously this will only work for cases like yours where the databases are on the same server/connection with the same credentials, but if it works, I'm happy to work on a PR to give control over this via the config.

**Comment by seatechdev** [comment]
Thanks!  The reason I have separate databases is because I plan on moving them to different servers/connections once we launch so that there are no performance issues to the main app that is created to serve the customer need.  Blogging server and Forum servers are add ons to increase engagement.  I guess I will have to probably write a custom forum.  It doesn't mean that anything is wrong with your package.  I have looked at yours and Chatter.   I am having similar issues with Chatter also due to my own unique business need.  Thank you for your help and time.

**Comment by Riari** [comment]
No problem. Ultimately, I think this is a limitation of Laravel, or at least how Eloquent generates queries. I believe MySQL itself cannot support joins across multiple servers, so the only way to do this would be to send a query to each server separately and process the results entirely in PHP to get the data you need.

I do wonder if there might be a better approach to your DB architecture that would work with Eloquent out of the box while being as scalable as you need, but that's a whole other topic.

Whatever you do, I hope you find a good solution!
