### ISSUE TITLE
If you dont have Livewire installed you cant install it

### ISSUE THREAD

**Issue by notwhoyouexpected** [Riari/laravel-forum#367]
Hi, if you try composer require riari/laravel-forum:^6.0 without having livewire installed it gives error messages...

**Comment by Riari** [comment]
Hi,

I'm pretty sure this is because the default config is set to use the livewire-tailwind preset. I've updated it in the latest release. Can you try again?

**Comment by Riari** [comment]
Going to assume this issue is resolved, but if you get any further errors, please let me know. Thanks!

**Comment by notwhoyouexpected** [comment]
Yeah i resolved it by installing livewire, installing the forum and deinstlalling livewire :)

**Comment by Riari** [comment]
Did you still need to do that with the latest release? If so then I need to do more research.

**Comment by notwhoyouexpected** [comment]
Not tested with last release but as last time was just testing and playing around and now i want to implement in the next days i will keep you updated if its still a issues with the newest release ;)

Also many thanks for maintaining such a nice package open source :)
