### ISSUE TITLE
change lang in forums

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#37]
is there a way to change the lang through extension?

**Comment by Riari** [comment]
Not sure what you mean by "through extension". You can change the locale in your config/app.php, or if you want to set it dynamically at runtime based on your users' preferences, you can use `app()->setLocale($locale)` (doing this in your middleware or a controller constructor seems sane).

The forums respect the locale, so you don't need to do anything specific with them unless you want to display the langcode in your URLs.

More here: http://laravel.com/docs/5.1/localization#introduction

**Comment by Denoder** [comment]
i meant like how would i go about extending your forum's en local so that i can change what's in it without having to create my own separate lang file. Kinda like how controllers and views are overwritten.

**Comment by Riari** [comment]
Right. You have to maintain your own copy of the lang file or edit the original. Conventionally, you'd copy it and the latest stable version of the forum does publish lang files along with config, views and migrations. The path should be `resources/lang/vendor/forum/en/base.php`

http://laravel.com/docs/5.1/localization#overriding-vendor-language-files

**Comment by Riari** [comment]
Also, I believe lang files are merged in a similar way to config, so you don't need to keep all the strings in your copy of the file, only the ones you actually want to change.
