### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#38]
This is somewhat unrelated to the forums itself or it could be beneficial to the forums. I was wondering if you have any idea how to implement notifications, I'm not looking for real-time notifications. Just notifications for when someone does something like follow you or, as a beneficiary to the forums when you're subscribed to it you could get notifications for when you subscribe to it.

I've spent months trying to figure notifications but its hard >_>

**Comment by flamerohr** [comment]
I can't remember if the forums package fire events on actions, vaguely remember it does? But you can listen to those events and send notifications as required based on events.

**Comment by Denoder** [comment]
All of the event cases are blank so i wouldn't know where to start utilizing them.

**Comment by flamerohr** [comment]
I'm on my phone at the moment, but you can define your own events in a self created service provider and go from there, here's some reference:
laravel.com/docs/5.1/events

**Comment by Riari** [comment]
V3 triggers some basic events (such as when viewing a thread), and yeah, writing your own events is an option if you can fire them. But you can also use [model events](http://laravel.com/docs/5.1/eloquent#events) to observe CRUD operations on the forum models and react on them however you like. See examples here: https://github.com/Riari/laravel-forum/tree/l5-refactor/src/Models/Observers (the classes in there are registered in the forum service provider).

As for notifications, this might give you a decent steer: http://ryantablada.com/post/an-eloquent-notification-strategy
