### ISSUE TITLE
Error When Viewing a Topic Reply Using Blade-Bootstrap

### ISSUE THREAD

**Issue by jhonatanluiz** [Riari/laravel-forum#386]
I am encountering an error when trying to view a reply to a topic while using the Blade-Bootstrap package in my Laravel application.

![erro-laravel-forum](https://github.com/user-attachments/assets/76df4552-1aac-4575-8026-2a1ac2a909c5)

**Comment by reniel-deang** [comment]
Same issue for blade-bootstrap preset, does you manage to fix it?

**Comment by Riari** [comment]
Hey,

Could you both confirm which package version you're using? I assume this is a problem caused by the latest release (6.0.12).

I'll take a look tonight and let you know as soon as I have a fix.

**Comment by reniel-deang** [comment]
yes, it is the latest release (6.0.12)

**Comment by jhonatanluiz** [comment]
Yes, I'm using version 6.0.12

**Comment by Riari** [comment]
This should be fixed in the new release (6.0.13). You'll need to re-install the `blade-bootstrap` preset to get the fixed views, or you can view the diff here if you'd prefer to fix them manually: https://github.com/Team-Tea-Time/laravel-forum/commit/b2e192c358e616d5bb4f6b03bef79a76018e21d3
