### ISSUE TITLE
mismatching between middleware and route

### ISSUE THREAD

**Issue by jifricherur** [Riari/laravel-forum#388]
i am new in forum.
here i am traying to authenticate, clear cache and not to return into dashboard without re-signing in Laravel 11
but i am failing. now that i deleted middleware routing then no error but the signing page existing. when signing with other  credentials that the previous credential has been loaded.
how to solve this conflict, can anyone help me
routes:
Route::group(['middleware' => ['Nocache']],( function(){
 Route::post('save/contactmsg',  [SaveController::class,'contactmsg'])->name ('contactmsg');
 Route::post('pages/save',  [SaveController::class,'saverate'])->name ('save');
 Route::post('save/searchresult',[SearchController::class,'searchfun']);
 Route::post('save/register', [SaveController::class, 'registerfun'])->name('save.register');
 Route::post('/save/userlogged',[UserController::class, 'userlogged'])->name('save.userlogged');
 Route::post('logout',[UserController::class, 'userlogout'])->name('logout');
    }) );

middleware:
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class Nocache
{
    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        return $next($request)->headers->set('Cache-Control', 'no-cache, no-store, max-age=0, must-revalidate')
        ->headers->set('Pragma', 'no-cache')
        ->headers->set('Expires', 'Fri, 01 Jan 1970 00:00:00 GMT');
    }
}

RouteServiceProvider:
<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * The path to your application's "home" route.
     *
     * Typically, users are redirected here after authentication.
     *
     * @var string
     */
    public const HOME = '/home';
    protected $namespace = 'App\Http\Controllers';
    //protected $livewirenamespace = 'App\Livewire';
    
    /**
     * Define your route model bindings, pattern filters, and other route configuration.
     */
    public function boot(): void
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });

        $this->routes(function () {
            

            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));
                

            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/user.php'));

                Route::middleware('Nocache')
                ->namespace($this->namespace)
                ->group(base_path('app\Http\Middleware\Nocache.php'));
                
        });
    }
}

Error: lluminate\Contracts\Container\BindingResolutionException
Target class [Nocache] does not exist.

**Comment by Riari** [comment]
Hi,

This seems to be unrelated to the Laravel Forum package. To clarify, this is not a forum for Laravel in general, it's a repository for a Laravel package that provides forum functionality. Please try elsewhere. There are several open communities focused on Laravel, e.g.:

* The [Laravel Discord server](https://discord.com/invite/laravel)
* The [LaraChat Slack community](https://larachat.co/)
* [Laracasts forum](https://laracasts.com/discuss)
* [Laravel.io forum](https://laravel.io/forum)
