### ISSUE TITLE
Not able to create or save

### ISSUE THREAD

**Issue by jetwes** [Riari/laravel-forum#4]
Hi,

i implented your package into my laravel 4.2 application. I can delete Threads or Posts, but i cannot edit or create them.
If i fill out the form and hit send - nothing happens - my app returns to the same page again. There are no alerts... Do you have a clue?

Thanks
Jens

**Comment by Riari** [comment]
Hi there,

I've just pushed a new release with a fix for this (the validation method was returning false regardless of passing - oops!)

It should work now, let me know if not.

Thanks

**Comment by jetwes** [comment]
Brilliant - thanks for the quick fix and your great package
