### ISSUE TITLE
call to undefined method ...ForumServiceProvider::mergeConfigFrom

### ISSUE THREAD

**Issue by bennok-tagoe** [Riari/laravel-forum#42]
I am having trouble publishing the package. I initially had trouble installing it using composer but that was solved by first installing laravel/support. Now I have added the service to my app file but when I try to run "php artisan vendor:publish" I get the following error. 

![untitled](https://cloud.githubusercontent.com/assets/12982264/9716261/a4566ae8-5557-11e5-8d60-8bd37b1558c1.jpg)

Not really sure where the problem is coming from...

**Comment by Riari** [comment]
Are you installing the package in an empty composer project? If you install it in a fresh Laravel 5/5.1 instance then all the dependencies should be satisfied and you won't get this error.

The `mergeConfigFrom()` method comes from [illuminate/support](https://packagist.org/packages/illuminate/support), although laravel/support (which is a third party package) also lists that as a dependency, so there may be something else missing too.

In any case, as long as your project has the same composer dependencies as Laravel, it should work:

```
"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.1.*"
},
```

**Comment by bennok-tagoe** [comment]
sorry forgot to mention, its laravel 4.2. Does that change anything?

**Comment by bennok-tagoe** [comment]
Also im installing it in an already running application. Will try again in a fresh installation

**Comment by Riari** [comment]
Ah, yes. The Laravel 4 version lives in a separate branch: https://github.com/Riari/laravel-forum/tree/laravel-4

**Comment by bennok-tagoe** [comment]
Thank You. Sorry for the bother.
