### ISSUE TITLE
Error trying to post new thread

### ISSUE THREAD

**Issue by z1haze** [Riari/laravel-forum#46]
Hi I have a fresh install of laravel 5.1 and a fresh install of your forum package. When I try to submit the form to post a new thread i am getting:

ErrorException in /home/vagrant/projects/ForumsExample/vendor/riari/laravel-forum/src/Riari/Forum/Models/Thread.php line 133:
Trying to get property of non-object

Thank you for looking into this.

**Comment by joselfonseca** [comment]
Hi there, this is also happening when opening a thread, i think is when it sets the view count, after a refresh it comes back normal, but every time you access a thread, this happens.
![screen shot 2015-09-15 at 9 04 50 am](https://cloud.githubusercontent.com/assets/2046653/9878624/4d744d02-5b89-11e5-9b9c-0a5097be68bb.png)
![screen shot 2015-09-15 at 9 05 17 am](https://cloud.githubusercontent.com/assets/2046653/9878629/51e99ebe-5b89-11e5-8708-0e0f7c5a0c2a.png)

**Comment by Riari** [comment]
Hi,

Thanks for reporting. Can one of you try the change I just committed? https://github.com/Riari/laravel-forum/commit/08579c27919046fb3f338c7bfb1fd6b01a41310d

**Comment by joselfonseca** [comment]
Seems to be fine now for me, Any chance you tag this please? Thanks!

**Comment by Riari** [comment]
Okay, I'll push a new release now :)
