### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by khendrickx** [Riari/laravel-forum#49]
When running the _php artisan vendor:publish_ command, the view, translation and migration files are copied every single time, not only the first time.
`Copied Directory [\vendor\riari\laravel-forum\src\views] To [\resources\views\vendor\forum]
Copied Directory [\vendor\riari\laravel-forum\src\translations] To [\resources\lang\vendor\forum]
Copied Directory [\vendor\riari\laravel-forum\src\migrations] To [\database\migrations]
`

Also, after running _composer update_, warnings are thrown notifying the migration classes already exists in the vendor folder.
`
Warning: Ambiguous class resolution, "CreateForumTableCategories" was found in both "$baseDir . '/database/migrations/2014_05_19_151759_create_forum_table_categories.php" and D:\Dropbox\Website\BIB\v3\vendor\riari\laravel-forum\src\migrations\2014_05_19_151759_create_forum_table_categories.php", the first will be used.
`

**Comment by Riari** [comment]
I think that publishing behaviour might be normal - or at least I hope it is, since I used the `publishes()` method as per [the docs](http://laravel.com/docs/5.1/packages#publishing-file-groups). It's not supposed to overwrite existing files, so if it's doing that in your case then something else must be wrong.

About the migrations, the ones in the package are autoloaded already, so it currently doesn't make sense for them to be published anyway. I'll remove the classmap key from `autoload` in composer.json to rectify that (since it currently only contains the migrations path).

**Comment by khendrickx** [comment]
I compared this package with others and on a fast first view I couldn't notice a difference with the usage of `publishes()`. However, other packages seems to copy their files just once, not at every `composer update`. I'm not yet entirely into packages, so I don't have an idea where to look for the problem but some others might?

**Comment by Riari** [comment]
Addressed the autoloading issue in the latest release. I'm still not sure about the issue with `publishes()`, but I'll leave this open until I can figure it out or someone is able to offer input. Thanks.

**Comment by morloderex** [comment]
The publishes funktion workes just perfectly but it's missing the translations files i have made a  PR to correct this.. :)

**Comment by gwcoyle** [comment]
I just tried to run php artisan vendor:publish

Upon doing so I get the following error

  [Symfony\Component\Debug\Exception\FatalErrorException]
  parse error, expecting `"identifier (T_STRING)"' or`"\ (T_NS_SEPARATOR)"'

Any ideas?

**Comment by Gummibeer** [comment]
the bouncer package does it with a custom check:

``` php
protected function publishMigrations()
    {
        if (class_exists('CreateBouncerTables')) {
            return;
        }

        $timestamp = date('Y_m_d_His', time());

        $stub = __DIR__.'/../migrations/create_bouncer_tables.php';

        $target = $this->app->databasePath().'/migrations/'.$timestamp.'_create_bouncer_tables.php';

        $this->publishes([$stub => $target], 'migrations');
    }
```

this allows the dev to rename the migration (the date) to bring it in right order with his own ones.
