### ISSUE TITLE
Manage Categories

### ISSUE THREAD

**Issue by mydnic** [Riari/laravel-forum#50]
Hello
I searched everywhere but I didn't find any way to manage categories and subCategories.. Is there a convenient way to do that ?

In my application I have an admin panel, so I created an Admin\ForumController that extends your \Riari\Forum\Controllers\BaseController

I then created a "create" and "store" methods with a custom form to add a category, but when I try to do this, for exemple : 

``` php
$category = [
      'parent_category' => $parent_category,
      'title'           => Input::get('title'),
      'subtitle'        => Input::get('subtitle'),
];
$this->categories->create($category);
```

I get a MassAssignmentException error..
($parent_category is "null")

What am I missing ?? ^^

Thanks by advance

**Comment by Riari** [comment]
Hi,

The Category model doesn't allow mass assignment out of the box - it probably should for this exact reason, so I'll change it soon. You do however have the option of extending the Category repository and model too, then overriding the constructor in your Admin\ForumController. You'd need to add a `protected $fillable = ['parent_category', 'title', 'subtitle'];` in your model, then replace the model used in your repository, then replace the repository used in your controller.

(Edit: Sorry, I completely overlooked the repository layer when I first posted this. Hopefully the workaround above still makes sense, but it's quite a lot to do for something so small. I'll try and get a new release out with the updated Category model tonight.)

Which version are you using, by the way? Laravel 5.x or 4.x?

**Comment by mydnic** [comment]
Thanks for your quick answer !
I'm using Laravel 5.0.*
I'll try to extend the model as you said.

Do you plan to add this change soon ? If so, I might just wait a bit ;)

**Comment by Riari** [comment]
Yeah, I just updated my comment - I'll make the change tonight. It should be available in about 5-6 hours :)

**Comment by mydnic** [comment]
You sir are awesome.

Many thanks !

**Comment by Riari** [comment]
New release is out. Please report back if you have any other difficulties.

**Comment by mydnic** [comment]
Seems to work fine ! Thanks :)
I'll continue building this admin panel and get back to you if I have any problem
Cheers

**Comment by mydnic** [comment]
I tried to build an "edit" page, but I don't find any way to select a single category by its ID, and return the variable to the view.
Is there any possibility to do something like this : <code>$category = $this->categories->find($id);</code> ??
The goal is to make a view with an edit form like this
<code>{!! Form::model($category, ['route' => ['admin.forum.category.update', $category->id], 'method' => 'put']) !!}</code>

Thanks in advance

**Comment by Riari** [comment]
Sure, take a look at the [BaseRepository](https://github.com/Riari/laravel-forum/blob/laravel-5/src/Riari/Forum/Repositories/BaseRepository.php) class - you can do `$this->categories->getByID($id);` :)

**Comment by mydnic** [comment]
Aaaw yeah ! I didn't see these :) Thanks
