### ISSUE TITLE
Estimation?

### ISSUE THREAD

**Issue by Denoder** [Riari/laravel-forum#51]
So what's the estimation for the completion of this update?

**Comment by Riari** [comment]
I'm not sure now. With the current change of plan (see #45), it could be at least another month, probably longer.

That said, the migrations will be compatible with v2 schema, so unless you change any existing columns, you do have the option of upgrading once 3.0.0 is released.

**Comment by Denoder** [comment]
im stalling on development until ur update is done.

**Comment by Riari** [comment]
There's nothing to stop you from using 2 until 3 is ready.

**Comment by Denoder** [comment]
i suppose

**Comment by Denoder** [comment]
How would i use the policies?

**Comment by Riari** [comment]
You would override the policy classes you want to override and change the classes referenced in [forum.integration.policies](https://github.com/Riari/laravel-forum/blob/l5-refactor/config/integration.php#L32). If you override any models, you can also change the ones used by the policies there.

That setup may change before 3.0.0 is released, but I doubt it.

**Comment by Denoder** [comment]
well the setup is okay but the delete parameters are non existent since the api was removed.

**Comment by Riari** [comment]
That's because it's not finished.

**Comment by Riari** [comment]
#45 updated. Work on this will resume this week.

**Comment by mydnic** [comment]
@Riari Sorry to comment on this old issue, I just didn't wanted to open a new issue for this quick question : 
I see you were talking about an upgrade guide from 2.x, any update on that ? I'm really looking forward  to it :)

**Comment by Riari** [comment]
Hey,

The upgrade is actually pretty simple now (I hope), depending on how much you changed your views in 2.x. I'll document this properly later, but for now, I would do the following:
1. Move any published laravel-forum config and views out of your project to ensure you get the new versions.
2. Update laravel-forum to 3.0 via composer: `composer require riari/laravel-forum:~3.0`
3. Install laravel-forum-frontend (unless you want to write your own): `composer require riari/laravel-forum-frontend:~1.0`
4. Publish files with `artisan vendor:publish`
5. Run new migrations with `artisan migrate`

That should bring your schema up to date. You can then go through the published views and config to bring them in line with whatever you had before.

Let me know if you run into any issues with that :)
