### ISSUE TITLE
Index view does not order Parent categories by Weight

### ISSUE THREAD

**Issue by mydnic** [Riari/laravel-forum#52]
Hi !

When I updated the weight attribute of my ParentCategories, in my database, the changes were not reflected in the Index view (so in /forum).

If I apply this change in the package, it works fine

``` php
public function getAll()
{
    return $this->model->where('parent_category', '=', null)->orderBy('weight')->get();
}
```

I just added ->orderBy

Is this state intentional ? Is there a way to do it without modifying the package ?

Thanks in advance

**Comment by Riari** [comment]
You're right, it's a bug. Fix incoming!
