### ISSUE TITLE
Number of database queries

### ISSUE THREAD

**Issue by ghuttu** [Riari/laravel-forum#53]
Hi, is it possible to reduce the number of database queries? For example in the category view I'm getting 132 queries with just nine threads listed:

"132 statements were executed, 28 of which were duplicated"

Maybe by using eager loading?

**Comment by Riari** [comment]
See #24; there's definitely some room for improvement here, although I consider it low priority as most of the queries in question are quite small. I doubt I'll invest any time towards this for v2, but it's definitely something I want to address in the rewrite (v3).

**Comment by ghuttu** [comment]
Cheers!
