### ISSUE TITLE
author_id, Please be more Eloquent Friendly

### ISSUE THREAD

**Issue by woodytang** [Riari/laravel-forum#55]
this is a great package, thank you!
just why using author_id instead of user_id in the database table?

this will cause Eloquent fail to work in some occasions, for example:

$user->forum_threads()->delete()

**Comment by Riari** [comment]
There's no reason to be honest, that's just the convention I ended up using. I'll probably update the migrations in the rewrite I'm doing to rename them.

That said, if you're going to define a threads relationship on your user model, you can at least specify the primary key name.

**Comment by woodytang** [comment]
Oh, that makes perfect sense! I am sorry I might have not been familiar with Eloquent, thank you!

**Comment by Riari** [comment]
No problem!
