### ISSUE TITLE
Extending BaseController for email notifications

### ISSUE THREAD

**Issue by SamBrownHTA** [Riari/laravel-forum#56]
I've created a new table called threads_notify, where the user who created a new thread will be able to select whether they receive notification emails.

I've added the model, repository and other code to the BaseContoller and it all works perfectly within the vendor folder files. But when I try to extend the code below into my ForumController I get the error: "Call to a member function getAll() on a non-object" on the category landing page (category.blade.php) and "Undefined variable: category" on the thread.blade.php page.

If I take out the variable declarations, __construct and load functions it displays perfectly, however when I try to create a new thread, I get "Undefined Property: ForumController::$threads"

How can I extend the Model, Repository and Controller functions to my App and make it work? I really don't want to have to backup these files every time I want to run an update.

```
    private $categories;
    private $threads;
    private $posts;
    private $notifications;

public function __construct(Categories $categories, Threads $threads, Posts $posts, Notifications $notify)
{
    $this->categories = $categories;
    $this->threads = $threads;
    $this->posts = $posts;
    $this->notifications = $notify;
}

protected function load($select = array(), $with = array())   
{
   $map_model_repos = array(
        'category'  => 'categories',
        'thread'    => 'threads',
        'post'      => 'posts',
        'notify'    => 'notifications'
    );
}

public function postCreateThread($categoryID, $categoryAlias)
{
    $user = Utils::getCurrentUser();

    $this->load(['category' => $categoryID]);

    $thread_valid = Validation::check('thread');
    $post_valid = Validation::check('post');
    if ($thread_valid && $post_valid)
    {
        $thread = array(
            'author_id'       => $user->id,
            'parent_category' => $categoryID,
            'title'           => Input::get('title')
        );

        $thread = $this->threads->create($thread);

        $post = array(
            'parent_thread'   => $thread->id,
            'author_id'       => $user->id,
            'content'         => Input::get('content')
        );

        $this->posts->create($post);

        $notify = array(
            'thread_id'   => $thread->id,
            'author_id'   => $user->id,
            'notify'      => Input::get('notify')
        );

        $this->notifications->create($notify);

        Alerts::add('success', trans('forum::base.thread_created'));

        return Redirect::to($thread->route);
    }
    else
    {
        return Redirect::to($this->collections['category']->newThreadRoute)->withInput();
    }
}
```

Model:

```
     <?php namespace Riari\Forum\Models;

    use Config;
    use Riari\Forum\Libraries\AccessControl;
    use Str;

    class Notify extends BaseModel {

        protected $table         = 'forum_threads_notify';
        public    $timestamps    = true;

        protected $guarded       = ['id'];
        protected $with          = ['author'];

        public function author()
        {
            return $this->belongsTo(Config::get('forum::integration.user_model'), 'author_id');
        }

    }
```

Repository:

```
   <?php namespace Riari\Forum\Repositories;

    use Riari\Forum\Models\Notify;

    class Notifications extends BaseRepository {

        public function __construct(Notify $model)
        {
            $this->model = $model;
        }
    }
```

**Comment by SamBrownHTA** [comment]
Then once this is working, I need to send an email every time someone replies to a thread.

I would need to check the database for notifcations, then probably add it to the function below ? 

public function postReplyToThread($categoryID, $categoryAlias, $threadID, $threadAlias)

**Comment by Riari** [comment]
Hi,

Assuming you're using the Laravel 4 version, I just pushed a new release that should fix the problem for you.

In any case, for what you're doing, may I suggest taking a look at [model events](http://laravel.com/docs/4.2/eloquent#model-events)? Seems like an ideal way to send out notifications :)

Cheers

**Comment by SamBrownHTA** [comment]
Thank you, and yes I am using 4.2.

Where should I place my Notify model and Notifications repository and how do I reference them in my ForumController?

**Comment by SamBrownHTA** [comment]
Repo

```
class Notifications extends Riari\Forum\Repositories\BaseRepository {

public function __construct(Notify $model)
{
    $this->model = $model;
}

public function getAll($threadID)
{
    return $this->model->where('notify', '=', 1)->where('thread_id', '=', $threadID)->get();
}
```

Model:

```
 use Riari\Forum\Libraries\AccessControl;

 class Notify extends Riari\Forum\Models\BaseModel {

   protected $table         = 'forum_threads_notify';
   public    $timestamps    = true;
   protected $guarded       = ['id'];    
```

I placed both files in my Models folder, copied the protected variables, the construct function (with my new notifications), the whole 'load' function (with new repo). I then added the mail after the construction of the notification record and all is working perfectly.
