### ISSUE TITLE
routes not working, getting 404

### ISSUE THREAD

**Issue by madita** [Riari/laravel-forum#60]
installed version 3.0 on Laravel 5.1. and I added "Riari\Forum\ForumServiceProvider::class", to config/app.php. The migration worked fine but after go to /forum I got my 404 page so what am I missing?

**Comment by Riari** [comment]
Do you have any "catch-all" routes defined in your application? If so, you may need to move the forum service provider before your other application ones.

**Comment by madita** [comment]
Thanks! That's it! Now I get this...
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'where clause' (SQL: select \* from `forum_categories` where (`category_id` = 0) order by `weight` desc)

Just to let you know, but I can fix that myself now :),

**Comment by Riari** [comment]
Okay, that's strange. The migrations should rename the column from `parent_category` to `category_id`. Did you get any errors when you ran them? Or is this on an application/DB that previously ran version 2?

**Comment by madita** [comment]
I deinstalled version 2 also everything in the migration table but probably not like I should do it...anyway the next thing is

Class 'Gate' not found

**Comment by Riari** [comment]
The Gate facade was added in Laravel 5.1.11, so either you're using an older version or you didn't add the facade as part of your upgrade. If it's the latter, just add this to your config/app.php aliases array:

```
'Gate'      => Illuminate\Support\Facades\Gate::class,
```

But to be honest, I want to avoid the use of facade aliases anywhere in the package for exactly this reason, so I'll change it in the next RC :)

**Comment by madita** [comment]
Great! Thank you very much!
