### ISSUE TITLE
"Maximum function nesting level of '100' reached, aborting!" In Laravel 5.1

### ISSUE THREAD

**Issue by martijn-heil** [Riari/laravel-forum#73]
I'm getting this error when trying to view the _/forum_ route. **Did this not appear to happen _before_ I created the first post**. But after I created that first post I can no longer view the forum index. I can view specific categories, posts and such, but not the forum index. I installed the Laravel 5 package using the installation instructions.

**`FatalErrorException in MySqlGrammar.php line 139:
Maximum function nesting level of '100' reached, aborting!`**
`in MySqlGrammar.php line 139`
`at FatalErrorException->__construct() in HandleExceptions.php line 127`
`at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php line 112`
`at HandleExceptions->handleShutdown() in HandleExceptions.php line 0`
`at MySqlGrammar->wrapValue() in Grammar.php line 79`
`at Grammar->wrap() in Grammar.php line 39`
`at Grammar->wrapTable() in Grammar.php line 77`
`at Grammar->wrap() in Grammar.php line 315`
`at Grammar->whereIn() in Grammar.php line 205`
`at Grammar->compileWheres() in Grammar.php line 62`
`at Grammar->compileComponents() in Grammar.php line 42`
`at Grammar->compileSelect() in MySqlGrammar.php line 36`
`at MySqlGrammar->compileSelect() in Builder.php line 1288`
`at Builder->toSql() in Builder.php line 1377`
`at Builder->runSelect() in Builder.php line 1367`
`at Builder->getFresh() in Builder.php line 1352`
`at Builder->get() in Builder.php line 404`
`at Builder->getModels() in Builder.php line 166`
`at Builder->get() in Relation.php line 284`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\Relation.php:284}() in Relation.php line 284`
`at Relation->__call() in Relation.php line 105`
`at BelongsTo->get() in Relation.php line 105`
`at Relation->getEager() in Builder.php line 455`
`at Builder->loadRelation() in Builder.php line 424`
`at Builder->eagerLoadRelations() in Builder.php line 172`
`at Builder->get() in Relation.php line 284`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\Relation.php:284}() in Relation.php line 284`
`at Relation->__call() in Relation.php line 105`
`at HasMany->get() in Relation.php line 105`
`at Relation->getEager() in Builder.php line 455`
`at Builder->loadRelation() in Builder.php line 424`
`at Builder->eagerLoadRelations() in Builder.php line 172`
`at Builder->get() in HasMany.php line 16`
`at HasMany->getResults() in Model.php line 2629`
`at Model->getRelationshipFromMethod() in Model.php line 2595`
`at Model->getRelationValue() in Model.php line 2537`
`at Model->getAttribute() in Model.php line 3254`
`at Model->__get() in Repository.php line 79`
`at Category->Riari\Forum\Models\{closure}() in Repository.php line 198`
`at Repository->remember() in CacheManager.php line 309`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php:309}() in CacheManager.php line 309`
`at CacheManager->__call() in Facade.php line 216`
`at CacheManager->remember() in Facade.php line 216`
`at Facade::__callStatic() in BaseModel.php line 29`
`at Cache::remember() in BaseModel.php line 29`
`at BaseModel->rememberAttribute() in Category.php line 80`
`at Category->getThreadCountAttribute() in Model.php line 2652`
`at Model->mutateAttribute() in Model.php line 2554`
`at Model->getAttributeValue() in Model.php line 2534`
`at Model->getAttribute() in Model.php line 3254`
`at Model->__get() in PhpEngine.php line 40
in PhpEngine.php line 40`
`at PhpEngine->evaluatePath() in CompilerEngine.php line 58`
`at CompilerEngine->get() in View.php line 137`
`at View->getContents() in View.php line 106`
`at View->renderContents() in View.php line 80`
`at View->render() in Response.php line 51`
`at Response->setContent() in Response.php line 202`
`at Response->__construct() in Router.php line 1223`
`at Router->prepareResponse() in ControllerDispatcher.php line 112`
`at ControllerDispatcher->Illuminate\Routing\{closure}() in Pipeline.php line 139`
`at call_user_func:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}() in Pipeline.php line 139`
`at Pipeline->Illuminate\Pipeline\{closure}() in Pipeline.php line 103`
`at call_user_func:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}() in Pipeline.php line 103`
`at Pipeline->then() in ControllerDispatcher.php line 113`
`at ControllerDispatcher->callWithinStack() in ControllerDispatcher.php line 68`
`at ControllerDispatcher->dispatch() in Route.php line 200`
`at Route->runWithCustomDispatcher() in Route.php line 133`
`at Route->run() in Router.php line 702`
`at Router->Illuminate\Routing\{closure}() in Pipeline.php line 139`
`at call_user_func:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}() in Pipeline.php line 139`
`at Pipeline->Illuminate\Pipeline\{closure}() in Pipeline.php line 103`
`at call_user_func:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}() in Pipeline.php line 103`
`at Pipeline->then() in Router.php line 704`
`at Router->runRouteWithinStack() in Router.php line 669`
`at Router->dispatchToRoute() in Router.php line 629`
`at Router->dispatch() in Kernel.php line 229`
`at Kernel->Illuminate\Foundation\Http\{closure}() in Pipeline.php line 139`
`at call_user_func:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}() in Pipeline.php line 139`
`at Pipeline->Illuminate\Pipeline\{closure}() in VerifyCsrfToken.php line 50`
`at VerifyCsrfToken->handle() in Pipeline.php line 124`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124`
`at Pipeline->Illuminate\Pipeline\{closure}() in ShareErrorsFromSession.php line 54`
`at ShareErrorsFromSession->handle() in Pipeline.php line 124`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124`
`at Pipeline->Illuminate\Pipeline\{closure}() in StartSession.php line 61`
`at StartSession->handle() in Pipeline.php line 124`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124`
`at Pipeline->Illuminate\Pipeline\{closure}() in AddQueuedCookiesToResponse.php line 37`
`at AddQueuedCookiesToResponse->handle() in Pipeline.php line 124`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124`
`at Pipeline->Illuminate\Pipeline\{closure}() in EncryptCookies.php line 59`
`at EncryptCookies->handle() in Pipeline.php line 124`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124`
`at Pipeline->Illuminate\Pipeline\{closure}() in CheckForMaintenanceMode.php line 42`
`at CheckForMaintenanceMode->handle() in Pipeline.php line 124`
`at call_user_func_array:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}() in Pipeline.php line 124`
`at Pipeline->Illuminate\Pipeline\{closure}() in Pipeline.php line 103`
`at call_user_func:{C:\wamp3\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}() in Pipeline.php line 103`
`at Pipeline->then() in Kernel.php line 118`
`at Kernel->sendRequestThroughRouter() in Kernel.php line 86`
`at Kernel->handle() in index.php line 54`
`at {main}() in index.php line 0`

**Comment by Riari** [comment]
What's your category hierarchy like? It may have something to do with the `deepestChild` attribute in the Category model, which is recursive (although it's cached by default).

In any case I would suggest increasing your [max_nesting_level](http://xdebug.org/docs/all_settings#max_nesting_level) config value as I don't think the default is enough for many projects nowadays. Personally I have mine set to 250.

Edit: just examined your stack trace and there's no sign of any calls to the `getDeepestChildAttribute()` method, which makes sense as it's not used in the views by default. I assume you're running version 3.0 though, correct me if I'm wrong.

**Comment by martijn-heil** [comment]
So after ages of trying to just disable xdebug, since I am not using it recently anyway. I finally managed to do so, wich fixed the error. As expected. Thanks anyway
