### ISSUE TITLE
Can't use published views 

### ISSUE THREAD

**Issue by flinux** [Riari/laravel-forum#8]
### Can't use published views

After following the instructions in the readme file:
- ##### Install the package via composer

``` sh
composer require riari/laravel-forum:~2.0
```
- ##### Then add the following service provider to your config/app.php

``` php
'Riari\Forum\ForumServiceProvider',
```
- ##### Run the vendor:publish command

``` sh
php artisan vendor:publish
```
- ##### Run migrations

``` sh
php artisan migrate
```

When i go in http://myurl.com/forum i see the views located in

``` sh
vendor/riari/laravel-forum/src/views
```

but not the ones copied by "vendor:publish" into 

``` sh
resources/views/forum
```

so i modified the ForumServiceProvider in this way:

``` php
$this->loadViewsFrom(__DIR__.'/../../../..'.'/../../'.'resources/'.'views/forum', 'forum');
```

but i don't think this is the right way to solve this problem.

**Comment by Riari** [comment]
OK, I see the problem. It's publishing the views into the wrong location. Laravel will automatically look for views under `resources/views/vendor/(namespace)` using the namespace passed into `loadViewsFrom()`, and the path in there is correct as it should point to the package views directory, but the `publishes()` call is missing the 'vendor' part.

I'll commit a fix and push a new release soon, but in the meantime just make sure any views you want to override are in `resources/views/vendor/forum` :)

Thanks.
