### ISSUE TITLE
Laravel Frontend with Laravel Forum 2

### ISSUE THREAD

**Issue by surfer190** [Riari/laravel-forum#83]
I was able to install the laravel frontend with the laravel forum 5.1 backend but now composer is failing:

```
composer require riari/laravel-forum-frontend:dev-master@dev
```

It complains that it is not acceptable, `laravel-forum`:`3.0.0` needs to be installed. But it worked on another pc earlier today.

**Comment by Riari** [comment]
Are you trying to use laravel-forum-frontend with laravel-forum 2.x.x? If so, they're not compatible. Versions prior to 3.0.0 have their front-end files included already.
