### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by MORRG** [Riari/laravel-forum#85]
All my routes work for editing and adding threads/posts but I get MethodNotAllowedHttpException if I try to Pin, Lock or Delete the same. As an example I've checked artisan route:list and can see listed:

portal/forum/{categoryID}-{categoryAlias}/{threadID}-{threadAlias}/post/{postID}/delete

and the url throwing the error is:

portal/forum/4-test/2-test/post/2/delete

Isn't this correct?

Thanks,

**Comment by Riari** [comment]
Are you using version 1 (Laravel 4.x) or version 2 (Laravel 5.x)?

In either case, have you changed/overridden the JS in the [master layout](https://github.com/Riari/laravel-forum/blob/laravel-5/src/views/layouts/master.blade.php)? If not, could you let me know which browser you're using?

**Comment by MORRG** [comment]
Thanks, replacing the master layout brought up the dialog as expected and functions great in Chrome but in Firefox the dialog appears but after clicking 'ok' nothing happens? Is there a fix I could apply to make it work in Firefox too? Thanks

**Comment by Riari** [comment]
I'm not sure. I need to debug it in Firefox. In the meantime, if you find a solution, please share :)

**Comment by MORRG** [comment]
The issue with Firefox appeared to be with the submission of the javascript form, Firefox requires the form to be in the DOM before submission, I've tweaked your javascript and added an additional div element below, I'm sure there's a cleaner way but this is what I've managed to get working.

The script now generates the form, adds it to the DOM and then submits.

Thanks for your support, great product.

```
<script>
$('a[data-confirm]').click(function(event) {
    if (!confirm('{!! trans('forum::base.generic_confirm') !!}')) {
        event.stopImmediatePropagation();
        event.preventDefault();
    }
});
$('[data-method]:not(.disabled)').click(function(event) {
    var form ='<form id="modifyform" action="' + $(this).attr('href') + '" method="POST">' +
    '<input type="hidden" name="_method" value="' + $(this).data('method') + '">' +
    '<input type="hidden" name="_token" value="{!! Session::getToken() !!}">' +
    '</form>';

  $( ".ForumModify" ).append( form );

   document.getElementById("modifyform").submit();

    event.preventDefault();
});
</script>

<div class="ForumModify"></div>
```

**Comment by Riari** [comment]
Great, I'll push out new releases with a fix to that effect. Thanks.
