### ISSUE TITLE
Installation issues with migrating

### ISSUE THREAD

**Issue by martijn-heil** [Riari/laravel-forum#86]
I'm getting this error when trying to migrate after a fresh installation of the 3.0 version, using the installation guide from the readme.

`[Doctrine\DBAL\Schema\SchemaException]`
`There is no column with name 'parent_category' on table 'forum_categories'.`

Exception trace:
http://pastebin.com/NAQFJKUW

Seems like a bug?

**Comment by Riari** [comment]
Yeah, there's a fix in the latest dev commit, I just haven't pushed a new release yet. I'll do that today :)

**Comment by martijn-heil** [comment]
Thanks :)

**Comment by kiluhr** [comment]
HELUP THAT LILL BOY HEELLLLLLLLLLLLLLLLLUP HIMMMMMMMMMMMMMMMMMMMM

**Comment by kiluhr** [comment]
that comment seems legit btw

**Comment by kiluhr** [comment]
pssst you have seen nothing dun ban me plix :)

**Comment by martijn-heil** [comment]
`3.0.0-RC6` /  `96b15a4` definitly didn't fix the bug..

**Comment by Riari** [comment]
Looking at your original comment again, it seems like you already have the up to date schema. Is that right?

**Comment by Riari** [comment]
Either the column is missing or it has already been renamed (it should end up being `category_id` as opposed to `parent_category`). I'm not sure how the error you're having can happen if you ran the migrations on a clean DB.

**Comment by martijn-heil** [comment]
Seems like there was something messed up with the migration system. I reset all migrations and ran them all again. That fixed it. Thanks anyway! (Awesome package btw ;) )
