### ISSUE TITLE
Error when I create category

### ISSUE THREAD

**Issue by ghost** [Riari/laravel-forum#88]
Hey!

When I add a category I have this error:

FatalErrorException in Stringy.php line 5:
Maximum function nesting level of '100' reached, aborting!

Can anyone help?

**Comment by Riari** [comment]
See #73. In short, increase your `xdebug.max_nesting_level` value (256 is suggested).

**Comment by ghost** [comment]
Thanks for you help!

**Comment by Riari** [comment]
No problem :)
