### ISSUE TITLE
Question: How to get post count across category?

### ISSUE THREAD

**Issue by Dreaw** [Riari/laravel-forum#91]
Hi,

Is there any possibility to get count of posts across category?

Eg: Category have 4 threads. Two threads have 10 posts and next two threads have 5 posts. How can I get number 30?

Thank you!

**Comment by breakeryouko** [comment]
What do you think about a select num_rows of posts based on category_id inner join on thread_id?

**Comment by Riari** [comment]
Yeah, that would work, unless you wanted to include posts from threads in subcategories as well.

**Comment by breakeryouko** [comment]
You are right.
I guess it's possible to check until the last subcategories to, but I'm not sure about the query's performance.
My solution is: category_id = 1,
select all category_id where category_id = 1
count all post in category 1
foreach category_id (subcategories level 1) check for subcategories level 2
count all post in this category
and keep going

**Comment by Riari** [comment]
I think that would be OK, maybe with some caching. With some additions to the category table, I think this would be entirely doable in a single query, but I'm not sure if it would translate to the Eloquent way of doing things.

**Comment by Dreaw** [comment]
Thank you very much :)
