### ISSUE TITLE
Question: How can I make it so only the admin can create categories, delete posts, etc.

### ISSUE THREAD

**Issue by ghost** [Riari/laravel-forum#95]

**Comment by ghost** [comment]
Nevermind, I figured it out. I changed some of the policies in  /src/Policies/ to include

``` php
        if (Auth::user()->id == 1) {
            return true
        }
        else {
            return false;
        }
```

Sorry for the noob question

**Comment by Riari** [comment]
Glad you figured it out :)

Two things though;
1. If you edited the policy classes directly (under /vendor), your changes can be overwritten by Composer (sorry if you know about that already, just making sure). You should create your own policy classes to extend the provided ones and override any methods in there. See here for further explanation: http://teamteatime.net/docs/laravel-forum/3.x/policies.md
2. You can shorten that code to `return ($user->id == 1);`

**Comment by ghost** [comment]
Didn't know that, thanks
