### ISSUE TITLE
Issue with routing in laravel 5.2

### ISSUE THREAD

**Issue by alanaasmaa** [Riari/laravel-forum#97]
Undefined variable: errors (View: /home/vagrant/Code/Laravel/resources/views/vendor/forum/partials/alerts.blade.php) (View: /home/vagrant/Code/Laravel/resources/views/vendor/forum/partials/alerts.blade.php) (View: /home/vagrant/Code/Laravel/resources/views/vendor/forum/partials/alerts.blade.php)

**Comment by antonkomarev** [comment]
Fix: http://stackoverflow.com/questions/34438463/laravel-5-2-errors-not-appearing-in-blade/34439766#34439766

**Comment by antonkomarev** [comment]
I think it will be enough to add an ability to define route middleware in `forum.routing.php` config file, but it's https://github.com/Riari/laravel-forum-frontend issue.

**Comment by antonkomarev** [comment]
@Riari could you increment version with this patch, please?

**Comment by alanaasmaa** [comment]
Awesome its now updated but im thinking should i use riari or build new one :) 
But this bug seems to be now closed !

**Comment by Riari** [comment]
New release is out now, so you can use that.

Thanks again @a-komarev
