### ISSUE TITLE
CSRF token error

### ISSUE THREAD

**Issue by antonkomarev** [Riari/laravel-forum#99]
Categories creation is working, threads creation is throwing an error:

> TokenMismatchException in VerifyCsrfToken.php line 46

CSRF token exists in form & `web` middleware group is using.

Using clean latest Laravel 5.2 with clean https://github.com/Riari/laravel-forum-frontend

**Comment by Riari** [comment]
Closing this as I haven't been able to reproduce it with a fresh Laravel 5.2 project.
